const fs = require('fs');

const ukPath = 'C:/Users/michael/Desktop/ukrainian typing game/src/data/vocabulary/comprehensive-dictionary.json';
const ruPath = 'C:/Users/michael/Desktop/ukrainian typing game/src/data/ru/vocabulary/comprehensive-dictionary.json';

const ukData = JSON.parse(fs.readFileSync(ukPath, 'utf8'));
const ruData = JSON.parse(fs.readFileSync(ruPath, 'utf8'));

// Build lookup from en -> ru entry
const ruByEn = {};
for (const w of ruData.words) {
  ruByEn[w.en] = { ru: w.ru, phoneticRu: w.phonetic };
}

// Manual Russian translations for unmatched entries
const manualRu = {
  "to be": { ru: "быть", phoneticRu: "byt'" },
  "to have": { ru: "иметь", phoneticRu: "imet'" },
  "to look/to watch": { ru: "смотреть", phoneticRu: "smotret'" },
  "to listen": { ru: "слушать", phoneticRu: "slushat'" },
  "to walk": { ru: "ходить", phoneticRu: "khodit'" },
  "to go (by vehicle)": { ru: "ехать", phoneticRu: "yekhat'" },
  "to teach/to learn": { ru: "учить", phoneticRu: "uchit'" },
  "to study": { ru: "учиться", phoneticRu: "uchit'sya" },
  "to like/to please": { ru: "нравиться", phoneticRu: "nravit'sya" },
  "to begin/to start": { ru: "начинать", phoneticRu: "nachinat'" },
  "to ask": { ru: "спрашивать", phoneticRu: "sprashivat'" },
  "to answer": { ru: "отвечать", phoneticRu: "otvechat'" },
  "to remember": { ru: "помнить", phoneticRu: "pomnit'" },
  "to draw/to paint": { ru: "рисовать", phoneticRu: "risovat'" },
  "to clean/to tidy up": { ru: "убирать", phoneticRu: "ubirat'" },
  "to wake up": { ru: "просыпаться", phoneticRu: "prosypat'sya" },
  "to get dressed": { ru: "одеваться", phoneticRu: "odevat'sya" },
  "to bathe": { ru: "купаться", phoneticRu: "kupat'sya" },
  "to fly": { ru: "лететь", phoneticRu: "letet'" },
  "to swim": { ru: "плавать", phoneticRu: "plavat'" },
  "to fall": { ru: "падать", phoneticRu: "padat'" },
  "to throw": { ru: "бросать", phoneticRu: "brosat'" },
  "to catch": { ru: "ловить", phoneticRu: "lovit'" },
  "to carry/to wear": { ru: "носить", phoneticRu: "nosit'" },
  "to cut": { ru: "резать", phoneticRu: "rezat'" },
  "to build": { ru: "строить", phoneticRu: "stroit'" },
  "to break": { ru: "ломать", phoneticRu: "lomat'" },
  "to change": { ru: "менять", phoneticRu: "menyat'" },
  "to choose": { ru: "выбирать", phoneticRu: "vybirat'" },
  "to decide/to solve": { ru: "решать", phoneticRu: "reshat'" },
  "to try": { ru: "пытаться", phoneticRu: "pytat'sya" },
  "to fear/to be afraid": { ru: "бояться", phoneticRu: "boyat'sya" },
  "to call/to name": { ru: "звать", phoneticRu: "zvat'" },
  "to be born": { ru: "родиться", phoneticRu: "rodit'sya" },
  "to die": { ru: "умереть", phoneticRu: "umeret'" },
  "to grow": { ru: "расти", phoneticRu: "rasti" },
  "to show": { ru: "показывать", phoneticRu: "pokazyvat'" },
  "to hide": { ru: "прятать", phoneticRu: "pryatat'" },
  "to receive/to get": { ru: "получать", phoneticRu: "poluchat'" },
  "to return": { ru: "возвращаться", phoneticRu: "vozvrashchat'sya" },
  "to stay/to remain": { ru: "оставаться", phoneticRu: "ostavat'sya" },
  "to stop": { ru: "останавливаться", phoneticRu: "ostanavlivat'sya" },
  "to move": { ru: "двигаться", phoneticRu: "dvigat'sya" },
  "to touch": { ru: "трогать", phoneticRu: "trogat'" },
  "to hold": { ru: "держать", phoneticRu: "derzhat'" },
  "to pull": { ru: "тянуть", phoneticRu: "tyanut'" },
  "to push": { ru: "толкать", phoneticRu: "tolkat'" },
  "to carry": { ru: "нести", phoneticRu: "nesti" },
  "to climb/to go up": { ru: "подниматься", phoneticRu: "podnimat'sya" },
  "to go down/to descend": { ru: "спускаться", phoneticRu: "spuskat'sya" },
  "to enter": { ru: "входить", phoneticRu: "vkhodit'" },
  "to exit/to go out": { ru: "выходить", phoneticRu: "vykhodit'" },
  "to sit down": { ru: "сесть", phoneticRu: "sest'" },
  "to stand up/to get up": { ru: "встать", phoneticRu: "vstat'" },
  "to travel": { ru: "путешествовать", phoneticRu: "puteshestvovat'" },
  "to fly (regularly)": { ru: "летать", phoneticRu: "letat'" },
  "to call out": { ru: "звать", phoneticRu: "zvat'" },
  "to shout/to scream": { ru: "кричать", phoneticRu: "krichat'" },
  "to whisper": { ru: "шептать", phoneticRu: "sheptat'" },
  "to promise": { ru: "обещать", phoneticRu: "obeshchat'" },
  "to explain": { ru: "объяснять", phoneticRu: "ob'yasnyat'" },
  "to translate": { ru: "переводить", phoneticRu: "perevodit'" },
  "to tell/to narrate": { ru: "рассказывать", phoneticRu: "rasskazyvat'" },
  "to invite": { ru: "приглашать", phoneticRu: "priglashat'" },
  "to meet": { ru: "встречать", phoneticRu: "vstrechat'" },
  "to say goodbye": { ru: "прощаться", phoneticRu: "proshchat'sya" },
  "to kiss": { ru: "целовать", phoneticRu: "tselovat'" },
  "to hug": { ru: "обнимать", phoneticRu: "obnimat'" },
  "man/husband": { ru: "мужчина/муж", phoneticRu: "muzhchina/muzh" },
  "woman/wife": { ru: "женщина/жена", phoneticRu: "zhenshchina/zhena" },
  "boy/guy": { ru: "парень", phoneticRu: "paren'" },
  "girl/girlfriend": { ru: "девушка", phoneticRu: "devushka" },
  "baby/infant": { ru: "младенец", phoneticRu: "mladenets" },
  "female friend": { ru: "подруга", phoneticRu: "podruga" },
  "enemy": { ru: "враг", phoneticRu: "vrag" },
  "hero": { ru: "герой", phoneticRu: "geroy" },
  "people/nation": { ru: "народ", phoneticRu: "narod" },
  "citizen": { ru: "гражданин", phoneticRu: "grazhdanin" },
  "mom/mother": { ru: "мама", phoneticRu: "mama" },
  "dad": { ru: "папа", phoneticRu: "papa" },
  "son": { ru: "сын", phoneticRu: "syn" },
  "daughter": { ru: "дочь", phoneticRu: "doch'" },
  "grandson": { ru: "внук", phoneticRu: "vnuk" },
  "granddaughter": { ru: "внучка", phoneticRu: "vnuchka" },
  "uncle": { ru: "дядя", phoneticRu: "dyadya" },
  "aunt": { ru: "тётя", phoneticRu: "tyotya" },
  "nephew": { ru: "племянник", phoneticRu: "plemyannik" },
  "niece": { ru: "племянница", phoneticRu: "plemyannitsa" },
  "cousin (male)": { ru: "двоюродный брат", phoneticRu: "dvoyurodnyy brat" },
  "cousin (female)": { ru: "двоюродная сестра", phoneticRu: "dvoyurodnaya sestra" },
  "fiance/groom": { ru: "жених", phoneticRu: "zhenikh" },
  "fiancee/bride": { ru: "невеста", phoneticRu: "nevesta" },
  "mother-in-law (husband's)": { ru: "свекровь", phoneticRu: "svekrov'" },
  "mother-in-law (wife's)": { ru: "тёща", phoneticRu: "tyoshcha" },
  "home/house": { ru: "дом", phoneticRu: "dom" },
  "building/house": { ru: "здание/дом", phoneticRu: "zdaniye/dom" },
  "apartment": { ru: "квартира", phoneticRu: "kvartira" },
  "room": { ru: "комната", phoneticRu: "komnata" },
  "kitchen": { ru: "кухня", phoneticRu: "kukhnya" },
  "bathroom/bathtub": { ru: "ванная", phoneticRu: "vannaya" },
  "bedroom": { ru: "спальня", phoneticRu: "spal'nya" },
  "living room": { ru: "гостиная", phoneticRu: "gostinaya" },
  "floor": { ru: "пол", phoneticRu: "pol" },
  "ceiling": { ru: "потолок", phoneticRu: "potolok" },
  "wall": { ru: "стена", phoneticRu: "stena" },
  "stairs": { ru: "лестница", phoneticRu: "lestnitsa" },
  "roof": { ru: "крыша", phoneticRu: "krysha" },
  "garden": { ru: "сад", phoneticRu: "sad" },
  "yard/courtyard": { ru: "двор", phoneticRu: "dvor" },
  "city/town": { ru: "город", phoneticRu: "gorod" },
  "village": { ru: "деревня", phoneticRu: "derevnya" },
  "street": { ru: "улица", phoneticRu: "ulitsa" },
  "road": { ru: "дорога", phoneticRu: "doroga" },
  "way/path": { ru: "путь", phoneticRu: "put'" },
  "bridge": { ru: "мост", phoneticRu: "most" },
  "square/plaza": { ru: "площадь", phoneticRu: "ploshchad'" },
  "park": { ru: "парк", phoneticRu: "park" },
  "forest": { ru: "лес", phoneticRu: "les" },
  "mountain": { ru: "гора", phoneticRu: "gora" },
  "river": { ru: "река", phoneticRu: "reka" },
  "lake": { ru: "озеро", phoneticRu: "ozero" },
  "sea": { ru: "море", phoneticRu: "more" },
  "ocean": { ru: "океан", phoneticRu: "okean" },
  "island": { ru: "остров", phoneticRu: "ostrov" },
  "beach": { ru: "пляж", phoneticRu: "plyazh" },
  "field": { ru: "поле", phoneticRu: "pole" },
  "earth/land/ground": { ru: "земля", phoneticRu: "zemlya" },
  "sky": { ru: "небо", phoneticRu: "nebo" },
  "school": { ru: "школа", phoneticRu: "shkola" },
  "university": { ru: "университет", phoneticRu: "universitet" },
  "hospital": { ru: "больница", phoneticRu: "bol'nitsa" },
  "pharmacy": { ru: "аптека", phoneticRu: "apteka" },
  "shop/store": { ru: "магазин", phoneticRu: "magazin" },
  "market": { ru: "рынок", phoneticRu: "rynok" },
  "restaurant": { ru: "ресторан", phoneticRu: "restoran" },
  "cafe": { ru: "кафе", phoneticRu: "kafe" },
  "hotel": { ru: "гостиница", phoneticRu: "gostinitsa" },
  "bank": { ru: "банк", phoneticRu: "bank" },
  "post office/mail": { ru: "почта", phoneticRu: "pochta" },
  "library": { ru: "библиотека", phoneticRu: "biblioteka" },
  "museum": { ru: "музей", phoneticRu: "muzey" },
  "theater": { ru: "театр", phoneticRu: "teatr" },
  "cinema": { ru: "кино", phoneticRu: "kino" },
  "church": { ru: "церковь", phoneticRu: "tserkov'" },
  "train station": { ru: "вокзал", phoneticRu: "vokzal" },
  "airport": { ru: "аэропорт", phoneticRu: "aeroport" },
  "bus stop": { ru: "остановка", phoneticRu: "ostanovka" },
  "office": { ru: "офис", phoneticRu: "ofis" },
  "factory": { ru: "фабрика", phoneticRu: "fabrika" },
  "stadium": { ru: "стадион", phoneticRu: "stadion" },
  "country": { ru: "страна", phoneticRu: "strana" },
  "world": { ru: "мир", phoneticRu: "mir" },
  "sofa/couch": { ru: "диван", phoneticRu: "divan" },
  "wardrobe/closet": { ru: "шкаф", phoneticRu: "shkaf" },
  "shelf": { ru: "полка", phoneticRu: "polka" },
  "lock/castle": { ru: "замок", phoneticRu: "zamok" },
  "magazine": { ru: "журнал", phoneticRu: "zhurnal" },
  "letter/leaf": { ru: "лист/письмо", phoneticRu: "list/pis'mo" },
  "envelope": { ru: "конверт", phoneticRu: "konvert" },
  "pen": { ru: "ручка", phoneticRu: "ruchka" },
  "pencil": { ru: "карандаш", phoneticRu: "karandash" },
  "notebook": { ru: "тетрадь", phoneticRu: "tetrad'" },
  "paper": { ru: "бумага", phoneticRu: "bumaga" },
  "scissors": { ru: "ножницы", phoneticRu: "nozhnitsy" },
  "glass (drinking)": { ru: "стакан", phoneticRu: "stakan" },
  "bottle": { ru: "бутылка", phoneticRu: "butylka" },
  "pot/saucepan": { ru: "кастрюля", phoneticRu: "kastryulya" },
  "frying pan": { ru: "сковорода", phoneticRu: "skovoroda" },
  "towel": { ru: "полотенце", phoneticRu: "polotentse" },
  "soap": { ru: "мыло", phoneticRu: "mylo" },
  "toothbrush": { ru: "зубная щётка", phoneticRu: "zubnaya shchyotka" },
  "comb": { ru: "расчёска", phoneticRu: "raschyoska" },
  "umbrella": { ru: "зонт", phoneticRu: "zont" },
  "suitcase": { ru: "чемодан", phoneticRu: "chemodan" },
  "wallet": { ru: "кошелёк", phoneticRu: "koshelyok" },
  "phone/telephone": { ru: "телефон", phoneticRu: "telefon" },
  "television": { ru: "телевизор", phoneticRu: "televizor" },
  "camera": { ru: "камера", phoneticRu: "kamera" },
  "car/machine": { ru: "машина", phoneticRu: "mashina" },
  "bicycle": { ru: "велосипед", phoneticRu: "velosiped" },
  "toy": { ru: "игрушка", phoneticRu: "igrushka" },
  "photograph": { ru: "фотография", phoneticRu: "fotografiya" },
  "flower": { ru: "цветок", phoneticRu: "tsvetok" },
  "bread": { ru: "хлеб", phoneticRu: "khleb" },
  "butter/oil": { ru: "масло", phoneticRu: "maslo" },
  "cheese": { ru: "сыр", phoneticRu: "syr" },
  "egg": { ru: "яйцо", phoneticRu: "yaytso" },
  "meat": { ru: "мясо", phoneticRu: "myaso" },
  "chicken (meat)": { ru: "курятина", phoneticRu: "kuryatina" },
  "pork": { ru: "свинина", phoneticRu: "svinina" },
  "beef": { ru: "говядина", phoneticRu: "govyadina" },
  "fish": { ru: "рыба", phoneticRu: "ryba" },
  "rice": { ru: "рис", phoneticRu: "ris" },
  "pasta": { ru: "макароны", phoneticRu: "makarony" },
  "soup": { ru: "суп", phoneticRu: "sup" },
  "borscht": { ru: "борщ", phoneticRu: "borshch" },
  "salad": { ru: "салат", phoneticRu: "salat" },
  "porridge": { ru: "каша", phoneticRu: "kasha" },
  "pizza": { ru: "пицца", phoneticRu: "pitstsa" },
  "sandwich": { ru: "бутерброд", phoneticRu: "buterbrod" },
  "dumplings": { ru: "вареники", phoneticRu: "vareniki" },
  "pancakes/crepes": { ru: "блины", phoneticRu: "bliny" },
  "lard/cured pork fat": { ru: "сало", phoneticRu: "salo" },
  "sausage": { ru: "колбаса", phoneticRu: "kolbasa" },
  "sour cream": { ru: "сметана", phoneticRu: "smetana" },
  "milk": { ru: "молоко", phoneticRu: "moloko" },
  "yogurt": { ru: "йогурт", phoneticRu: "yogurt" },
  "ice cream": { ru: "мороженое", phoneticRu: "morozhenoye" },
  "cake": { ru: "торт", phoneticRu: "tort" },
  "cookies/biscuits": { ru: "печенье", phoneticRu: "pechen'ye" },
  "candy": { ru: "конфета", phoneticRu: "konfeta" },
  "chocolate": { ru: "шоколад", phoneticRu: "shokolad" },
  "honey": { ru: "мёд", phoneticRu: "myod" },
  "sugar": { ru: "сахар", phoneticRu: "sakhar" },
  "salt": { ru: "соль", phoneticRu: "sol'" },
  "pepper": { ru: "перец", phoneticRu: "perets" },
  "oil (cooking)": { ru: "масло", phoneticRu: "maslo" },
  "vinegar": { ru: "уксус", phoneticRu: "uksus" },
  "sauce": { ru: "соус", phoneticRu: "sous" },
  "ketchup": { ru: "кетчуп", phoneticRu: "ketchup" },
  "mustard": { ru: "горчица", phoneticRu: "gorchitsa" },
  "apple": { ru: "яблоко", phoneticRu: "yabloko" },
  "banana": { ru: "банан", phoneticRu: "banan" },
  "orange (fruit)": { ru: "апельсин", phoneticRu: "apel'sin" },
  "lemon": { ru: "лимон", phoneticRu: "limon" },
  "grapes": { ru: "виноград", phoneticRu: "vinograd" },
  "strawberry": { ru: "клубника", phoneticRu: "klubnika" },
  "cherry": { ru: "вишня", phoneticRu: "vishnya" },
  "plum": { ru: "слива", phoneticRu: "sliva" },
  "peach": { ru: "персик", phoneticRu: "persik" },
  "watermelon": { ru: "арбуз", phoneticRu: "arbuz" },
  "melon": { ru: "дыня", phoneticRu: "dynya" },
  "pear": { ru: "груша", phoneticRu: "grusha" },
  "pineapple": { ru: "ананас", phoneticRu: "ananas" },
  "raspberry": { ru: "малина", phoneticRu: "malina" },
  "blueberry": { ru: "черника", phoneticRu: "chernika" },
  "potato": { ru: "картошка", phoneticRu: "kartoshka" },
  "carrot": { ru: "морковь", phoneticRu: "morkov'" },
  "onion": { ru: "лук", phoneticRu: "luk" },
  "garlic": { ru: "чеснок", phoneticRu: "chesnok" },
  "tomato": { ru: "помидор", phoneticRu: "pomidor" },
  "cucumber": { ru: "огурец", phoneticRu: "ogurets" },
  "cabbage": { ru: "капуста", phoneticRu: "kapusta" },
  "beetroot": { ru: "свёкла", phoneticRu: "svyokla" },
  "mushroom": { ru: "гриб", phoneticRu: "grib" },
  "peas": { ru: "горох", phoneticRu: "gorokh" },
  "beans": { ru: "фасоль", phoneticRu: "fasol'" },
  "corn": { ru: "кукуруза", phoneticRu: "kukuruza" },
  "pumpkin": { ru: "тыква", phoneticRu: "tykva" },
  "nut": { ru: "орех", phoneticRu: "orekh" },
  "seeds": { ru: "семена", phoneticRu: "semena" },
  "water": { ru: "вода", phoneticRu: "voda" },
  "tea": { ru: "чай", phoneticRu: "chay" },
  "coffee": { ru: "кофе", phoneticRu: "kofe" },
  "juice": { ru: "сок", phoneticRu: "sok" },
  "beer": { ru: "пиво", phoneticRu: "pivo" },
  "wine": { ru: "вино", phoneticRu: "vino" },
  "compote": { ru: "компот", phoneticRu: "kompot" },
  "lemonade": { ru: "лимонад", phoneticRu: "limonad" },
  "head": { ru: "голова", phoneticRu: "golova" },
  "face": { ru: "лицо", phoneticRu: "litso" },
  "eye": { ru: "глаз", phoneticRu: "glaz" },
  "nose": { ru: "нос", phoneticRu: "nos" },
  "mouth": { ru: "рот", phoneticRu: "rot" },
  "ear": { ru: "ухо", phoneticRu: "ukho" },
  "hair": { ru: "волосы", phoneticRu: "volosy" },
  "tooth": { ru: "зуб", phoneticRu: "zub" },
  "tongue": { ru: "язык", phoneticRu: "yazyk" },
  "lip": { ru: "губа", phoneticRu: "guba" },
  "neck": { ru: "шея", phoneticRu: "sheya" },
  "shoulder": { ru: "плечо", phoneticRu: "plecho" },
  "hand/arm": { ru: "рука", phoneticRu: "ruka" },
  "finger/toe": { ru: "палец", phoneticRu: "palets" },
  "leg/foot": { ru: "нога", phoneticRu: "noga" },
  "knee": { ru: "колено", phoneticRu: "koleno" },
  "back": { ru: "спина", phoneticRu: "spina" },
  "chest": { ru: "грудь", phoneticRu: "grud'" },
  "stomach/belly": { ru: "живот", phoneticRu: "zhivot" },
  "heart": { ru: "сердце", phoneticRu: "serdtse" },
  "blood": { ru: "кровь", phoneticRu: "krov'" },
  "bone": { ru: "кость", phoneticRu: "kost'" },
  "skin": { ru: "кожа", phoneticRu: "kozha" },
  "brain": { ru: "мозг", phoneticRu: "mozg" },
  "elbow": { ru: "локоть", phoneticRu: "lokot'" },
  "shirt": { ru: "рубашка", phoneticRu: "rubashka" },
  "pants/trousers": { ru: "штаны", phoneticRu: "shtany" },
  "skirt": { ru: "юбка", phoneticRu: "yubka" },
  "dress": { ru: "платье", phoneticRu: "plat'ye" },
  "jacket/blazer": { ru: "пиджак", phoneticRu: "pidzhak" },
  "jacket/coat": { ru: "куртка", phoneticRu: "kurtka" },
  "coat/overcoat": { ru: "пальто", phoneticRu: "pal'to" },
  "sweater": { ru: "свитер", phoneticRu: "sviter" },
  "t-shirt": { ru: "футболка", phoneticRu: "futbolka" },
  "socks": { ru: "носки", phoneticRu: "noski" },
  "shoes/footwear": { ru: "обувь", phoneticRu: "obuv'" },
  "boots": { ru: "ботинки", phoneticRu: "botinki" },
  "sneakers": { ru: "кроссовки", phoneticRu: "krossovki" },
  "hat": { ru: "шляпа", phoneticRu: "shlyapa" },
  "winter hat/beanie": { ru: "шапка", phoneticRu: "shapka" },
  "gloves/mittens": { ru: "перчатки", phoneticRu: "perchatki" },
  "scarf": { ru: "шарф", phoneticRu: "sharf" },
  "necktie": { ru: "галстук", phoneticRu: "galstuk" },
  "belt": { ru: "ремень", phoneticRu: "remen'" },
  "glasses/eyeglasses": { ru: "очки", phoneticRu: "ochki" },
  "heel": { ru: "каблук", phoneticRu: "kabluk" },
  "button": { ru: "пуговица", phoneticRu: "pugovitsa" },
  "pocket": { ru: "карман", phoneticRu: "karman" },
  "nurse": { ru: "медсестра", phoneticRu: "medsestra" },
  "engineer": { ru: "инженер", phoneticRu: "inzhener" },
  "programmer": { ru: "программист", phoneticRu: "programmist" },
  "driver": { ru: "водитель", phoneticRu: "voditel'" },
  "chef/cook": { ru: "повар", phoneticRu: "povar" },
  "seller/salesperson": { ru: "продавец", phoneticRu: "prodavets" },
  "police officer": { ru: "полицейский", phoneticRu: "politseyskiy" },
  "firefighter": { ru: "пожарный", phoneticRu: "pozharnyy" },
  "lawyer": { ru: "адвокат", phoneticRu: "advokat" },
  "judge": { ru: "судья", phoneticRu: "sud'ya" },
  "journalist": { ru: "журналист", phoneticRu: "zhurnalist" },
  "writer": { ru: "писатель", phoneticRu: "pisatel'" },
  "artist/painter": { ru: "художник", phoneticRu: "khudozhnik" },
  "musician": { ru: "музыкант", phoneticRu: "muzykant" },
  "actor": { ru: "актёр", phoneticRu: "aktyor" },
  "farmer": { ru: "фермер", phoneticRu: "fermer" },
  "construction worker": { ru: "строитель", phoneticRu: "stroitel'" },
  "hairdresser": { ru: "парикмахер", phoneticRu: "parikmakher" },
  "pilot": { ru: "пилот", phoneticRu: "pilot" },
  "soldier": { ru: "солдат", phoneticRu: "soldat" },
  "accountant": { ru: "бухгалтер", phoneticRu: "bukhgalter" },
  "architect": { ru: "архитектор", phoneticRu: "arkhitektor" },
  "scientist": { ru: "учёный", phoneticRu: "uchyonyy" },
  "dentist": { ru: "стоматолог", phoneticRu: "stomatolog" },
  "veterinarian": { ru: "ветеринар", phoneticRu: "veterinar" },
  "time": { ru: "время", phoneticRu: "vremya" },
  "hour": { ru: "час", phoneticRu: "chas" },
  "minute": { ru: "минута", phoneticRu: "minuta" },
  "second": { ru: "секунда", phoneticRu: "sekunda" },
  "day": { ru: "день", phoneticRu: "den'" },
  "night": { ru: "ночь", phoneticRu: "noch'" },
  "morning": { ru: "утро", phoneticRu: "utro" },
  "evening": { ru: "вечер", phoneticRu: "vecher" },
  "week": { ru: "неделя", phoneticRu: "nedelya" },
  "month/moon": { ru: "месяц", phoneticRu: "mesyats" },
  "year": { ru: "год", phoneticRu: "god" },
  "today": { ru: "сегодня", phoneticRu: "segodnya" },
  "yesterday": { ru: "вчера", phoneticRu: "vchera" },
  "tomorrow": { ru: "завтра", phoneticRu: "zavtra" },
  "now": { ru: "сейчас", phoneticRu: "seychas" },
  "then/later": { ru: "потом", phoneticRu: "potom" },
  "earlier/before": { ru: "раньше", phoneticRu: "ran'she" },
  "soon": { ru: "скоро", phoneticRu: "skoro" },
  "always": { ru: "всегда", phoneticRu: "vsegda" },
  "never": { ru: "никогда", phoneticRu: "nikogda" },
  "sometimes": { ru: "иногда", phoneticRu: "inogda" },
  "often": { ru: "часто", phoneticRu: "chasto" },
  "rarely": { ru: "редко", phoneticRu: "redko" },
  "Monday": { ru: "понедельник", phoneticRu: "ponedel'nik" },
  "Tuesday": { ru: "вторник", phoneticRu: "vtornik" },
  "Wednesday": { ru: "среда", phoneticRu: "sreda" },
  "Thursday": { ru: "четверг", phoneticRu: "chetverg" },
  "Friday": { ru: "пятница", phoneticRu: "pyatnitsa" },
  "Saturday": { ru: "суббота", phoneticRu: "subbota" },
  "Sunday": { ru: "воскресенье", phoneticRu: "voskresen'ye" },
  "January": { ru: "январь", phoneticRu: "yanvar'" },
  "February": { ru: "февраль", phoneticRu: "fevral'" },
  "March": { ru: "март", phoneticRu: "mart" },
  "April": { ru: "апрель", phoneticRu: "aprel'" },
  "May": { ru: "май", phoneticRu: "may" },
  "June": { ru: "июнь", phoneticRu: "iyun'" },
  "July": { ru: "июль", phoneticRu: "iyul'" },
  "August": { ru: "август", phoneticRu: "avgust" },
  "September": { ru: "сентябрь", phoneticRu: "sentyabr'" },
  "October": { ru: "октябрь", phoneticRu: "oktyabr'" },
  "November": { ru: "ноябрь", phoneticRu: "noyabr'" },
  "December": { ru: "декабрь", phoneticRu: "dekabr'" },
  "spring": { ru: "весна", phoneticRu: "vesna" },
  "summer": { ru: "лето", phoneticRu: "leto" },
  "autumn/fall": { ru: "осень", phoneticRu: "osen'" },
  "winter": { ru: "зима", phoneticRu: "zima" },
  "zero": { ru: "ноль", phoneticRu: "nol'" },
  "one": { ru: "один", phoneticRu: "odin" },
  "two": { ru: "два", phoneticRu: "dva" },
  "three": { ru: "три", phoneticRu: "tri" },
  "four": { ru: "четыре", phoneticRu: "chetyre" },
  "five": { ru: "пять", phoneticRu: "pyat'" },
  "six": { ru: "шесть", phoneticRu: "shest'" },
  "seven": { ru: "семь", phoneticRu: "sem'" },
  "eight": { ru: "восемь", phoneticRu: "vosem'" },
  "nine": { ru: "девять", phoneticRu: "devyat'" },
  "ten": { ru: "десять", phoneticRu: "desyat'" },
  "eleven": { ru: "одиннадцать", phoneticRu: "odinnadtsat'" },
  "twelve": { ru: "двенадцать", phoneticRu: "dvenadtsat'" },
  "twenty": { ru: "двадцать", phoneticRu: "dvadtsat'" },
  "thirty": { ru: "тридцать", phoneticRu: "tridtsat'" },
  "forty": { ru: "сорок", phoneticRu: "sorok" },
  "fifty": { ru: "пятьдесят", phoneticRu: "pyat'desyat" },
  "hundred": { ru: "сто", phoneticRu: "sto" },
  "thousand": { ru: "тысяча", phoneticRu: "tysyacha" },
  "million": { ru: "миллион", phoneticRu: "million" },
  "first": { ru: "первый", phoneticRu: "pervyy" },
  "second (ordinal)": { ru: "второй", phoneticRu: "vtoroy" },
  "third": { ru: "третий", phoneticRu: "tretiy" },
  "last": { ru: "последний", phoneticRu: "posledniy" },
  "short (length)": { ru: "короткий", phoneticRu: "korotkiy" },
  "low/short (height)": { ru: "низкий", phoneticRu: "nizkiy" },
  "thick/fat": { ru: "толстый", phoneticRu: "tolstyy" },
  "thin": { ru: "тонкий", phoneticRu: "tonkiy" },
  "good/kind": { ru: "добрый", phoneticRu: "dobryy" },
  "beautiful/pretty/nice": { ru: "красивый", phoneticRu: "krasivyy" },
  "ugly": { ru: "уродливый", phoneticRu: "urodlivyy" },
  "cool": { ru: "прохладный", phoneticRu: "prokhladnyy" },
  "wet": { ru: "мокрый", phoneticRu: "mokryy" },
  "dry": { ru: "сухой", phoneticRu: "sukhoy" },
  "heavy/difficult": { ru: "тяжёлый", phoneticRu: "tyazhyolyy" },
  "weak": { ru: "слабый", phoneticRu: "slabyy" },
  "clean": { ru: "чистый", phoneticRu: "chistyy" },
  "correct/right": { ru: "правильный", phoneticRu: "pravil'nyy" },
  "wrong/incorrect": { ru: "неправильный", phoneticRu: "nepravil'nyy" },
  "interesting": { ru: "интересный", phoneticRu: "interesnyy" },
  "boring": { ru: "скучный", phoneticRu: "skuchnyy" },
  "dangerous": { ru: "опасный", phoneticRu: "opasnyy" },
  "safe": { ru: "безопасный", phoneticRu: "bezopasnyy" },
  "famous/known": { ru: "известный", phoneticRu: "izvestnyy" },
  "busy/occupied": { ru: "занятый", phoneticRu: "zanyatyy" },
  "alive/lively": { ru: "живой", phoneticRu: "zhivoy" },
  "dead": { ru: "мёртвый", phoneticRu: "myortvyy" },
  "hungry": { ru: "голодный", phoneticRu: "golodnyy" },
  "full (not hungry)": { ru: "сытый", phoneticRu: "sytyy" },
  "sick/ill": { ru: "больной", phoneticRu: "bol'noy" },
  "healthy": { ru: "здоровый", phoneticRu: "zdorovyy" },
  "tired": { ru: "усталый", phoneticRu: "ustalyy" },
  "calm/peaceful": { ru: "спокойный", phoneticRu: "spokoynyy" },
  "funny": { ru: "смешной", phoneticRu: "smeshnoy" },
  "serious": { ru: "серьёзный", phoneticRu: "ser'yoznyy" },
  "complex/complicated": { ru: "сложный", phoneticRu: "slozhnyy" },
  "possible": { ru: "возможный", phoneticRu: "vozmozhnyy" },
  "impossible": { ru: "невозможный", phoneticRu: "nevozmozhnyy" },
  "necessary/needed": { ru: "нужный", phoneticRu: "nuzhnyy" },
  "different/various": { ru: "разный", phoneticRu: "raznyy" },
  "same/identical": { ru: "одинаковый", phoneticRu: "odinakovyy" },
  "full/complete": { ru: "полный", phoneticRu: "polnyy" },
  "empty": { ru: "пустой", phoneticRu: "pustoy" },
  "quiet": { ru: "тихий", phoneticRu: "tikhiy" },
  "hard/solid": { ru: "твёрдый", phoneticRu: "tvyordyy" },
  "sharp": { ru: "острый", phoneticRu: "ostryy" },
  "round": { ru: "круглый", phoneticRu: "kruglyy" },
  "straight/direct": { ru: "прямой", phoneticRu: "pryamoy" },
  "tasty/delicious": { ru: "вкусный", phoneticRu: "vkusnyy" },
  "sweet": { ru: "сладкий", phoneticRu: "sladkiy" },
  "sour": { ru: "кислый", phoneticRu: "kislyy" },
  "bitter": { ru: "горький", phoneticRu: "gor'kiy" },
  "salty": { ru: "солёный", phoneticRu: "solyonyy" },
  "spicy": { ru: "острый", phoneticRu: "ostryy" },
  "I": { ru: "я", phoneticRu: "ya" },
  "you (informal)": { ru: "ты", phoneticRu: "ty" },
  "he": { ru: "он", phoneticRu: "on" },
  "she": { ru: "она", phoneticRu: "ona" },
  "it": { ru: "оно", phoneticRu: "ono" },
  "we": { ru: "мы", phoneticRu: "my" },
  "you (formal/plural)": { ru: "вы", phoneticRu: "vy" },
  "they": { ru: "они", phoneticRu: "oni" },
  "my/mine": { ru: "мой", phoneticRu: "moy" },
  "your/yours (informal)": { ru: "твой", phoneticRu: "tvoy" },
  "his/its": { ru: "его", phoneticRu: "yego" },
  "her/hers": { ru: "её", phoneticRu: "yeyo" },
  "our/ours": { ru: "наш", phoneticRu: "nash" },
  "your/yours (formal)": { ru: "ваш", phoneticRu: "vash" },
  "their/theirs": { ru: "их", phoneticRu: "ikh" },
  "this (masc.)": { ru: "этот", phoneticRu: "etot" },
  "this (fem.)": { ru: "эта", phoneticRu: "eta" },
  "this (neut.)/this is": { ru: "это", phoneticRu: "eto" },
  "that (masc.)": { ru: "тот", phoneticRu: "tot" },
  "that (fem.)": { ru: "та", phoneticRu: "ta" },
  "that (neut.)": { ru: "то", phoneticRu: "to" },
  "who": { ru: "кто", phoneticRu: "kto" },
  "what/that": { ru: "что", phoneticRu: "chto" },
  "where": { ru: "где", phoneticRu: "gde" },
  "when": { ru: "когда", phoneticRu: "kogda" },
  "how": { ru: "как", phoneticRu: "kak" },
  "why": { ru: "почему", phoneticRu: "pochemu" },
  "how much/how many": { ru: "сколько", phoneticRu: "skol'ko" },
  "which/what kind": { ru: "какой", phoneticRu: "kakoy" },
  "nothing": { ru: "ничего", phoneticRu: "nichego" },
  "nobody/no one": { ru: "никто", phoneticRu: "nikto" },
  "everything/all": { ru: "всё", phoneticRu: "vsyo" },
  "everyone/all (people)": { ru: "все", phoneticRu: "vse" },
  "something": { ru: "что-то", phoneticRu: "chto-to" },
  "someone": { ru: "кто-то", phoneticRu: "kto-to" },
  "each/every": { ru: "каждый", phoneticRu: "kazhdyy" },
  "other/another": { ru: "другой", phoneticRu: "drugoy" },
  "self/oneself": { ru: "сам", phoneticRu: "sam" },
  "in/into": { ru: "в", phoneticRu: "v" },
  "in/at": { ru: "у", phoneticRu: "u" },
  "on/onto/at": { ru: "на", phoneticRu: "na" },
  "with/from": { ru: "с", phoneticRu: "s" },
  "to/until/before": { ru: "до", phoneticRu: "do" },
  "from": { ru: "от", phoneticRu: "ot" },
  "behind/for/beyond": { ru: "за", phoneticRu: "za" },
  "under": { ru: "под", phoneticRu: "pod" },
  "above/over": { ru: "над", phoneticRu: "nad" },
  "between": { ru: "между", phoneticRu: "mezhdu" },
  "in front of/before": { ru: "перед", phoneticRu: "pered" },
  "after": { ru: "после", phoneticRu: "posle" },
  "through/across/because of": { ru: "через", phoneticRu: "cherez" },
  "near/beside": { ru: "около", phoneticRu: "okolo" },
  "around": { ru: "вокруг", phoneticRu: "vokrug" },
  "without": { ru: "без", phoneticRu: "bez" },
  "for": { ru: "для", phoneticRu: "dlya" },
  "about/concerning": { ru: "о/про", phoneticRu: "o/pro" },
  "and": { ru: "и", phoneticRu: "i" },
  "or": { ru: "или", phoneticRu: "ili" },
  "but": { ru: "но", phoneticRu: "no" },
  "because": { ru: "потому что", phoneticRu: "potomu chto" },
  "if": { ru: "если", phoneticRu: "yesli" },
  "when/while": { ru: "когда", phoneticRu: "kogda" },
  "in order to/so that": { ru: "чтобы", phoneticRu: "chtoby" },
  "although/though": { ru: "хотя", phoneticRu: "khotya" },
  "however": { ru: "однако", phoneticRu: "odnako" },
  "here": { ru: "здесь", phoneticRu: "zdes'" },
  "there": { ru: "там", phoneticRu: "tam" },
  "very": { ru: "очень", phoneticRu: "ochen'" },
  "also/too": { ru: "тоже", phoneticRu: "tozhe" },
  "still/yet/more": { ru: "ещё", phoneticRu: "yeshchyo" },
  "already": { ru: "уже", phoneticRu: "uzhe" },
  "only": { ru: "только", phoneticRu: "tol'ko" },
  "together": { ru: "вместе", phoneticRu: "vmeste" },
  "separately": { ru: "отдельно", phoneticRu: "otdel'no" },
  "well/good": { ru: "хорошо", phoneticRu: "khorosho" },
  "badly": { ru: "плохо", phoneticRu: "plokho" },
  "quickly": { ru: "быстро", phoneticRu: "bystro" },
  "slowly": { ru: "медленно", phoneticRu: "medlenno" },
  "quietly": { ru: "тихо", phoneticRu: "tikho" },
  "loudly": { ru: "громко", phoneticRu: "gromko" },
  "far": { ru: "далеко", phoneticRu: "daleko" },
  "near/close": { ru: "близко", phoneticRu: "blizko" },
  "up/upward": { ru: "вверх", phoneticRu: "vverkh" },
  "down/downward": { ru: "вниз", phoneticRu: "vniz" },
  "forward": { ru: "вперёд", phoneticRu: "vperyod" },
  "back/backward": { ru: "назад", phoneticRu: "nazad" },
  "to the left": { ru: "налево", phoneticRu: "nalevo" },
  "to the right": { ru: "направо", phoneticRu: "napravo" },
  "straight ahead": { ru: "прямо", phoneticRu: "pryamo" },
  "on the contrary": { ru: "наоборот", phoneticRu: "naoborot" },
  "probably/surely": { ru: "наверное", phoneticRu: "navernoye" },
  "maybe/perhaps": { ru: "может быть", phoneticRu: "mozhet byt'" },
  "of course/usually": { ru: "конечно", phoneticRu: "konechno" },
  "yes/so": { ru: "да", phoneticRu: "da" },
  "no": { ru: "нет", phoneticRu: "net" },
  "not": { ru: "не", phoneticRu: "ne" },
  "very/very much": { ru: "очень", phoneticRu: "ochen'" },
  "a little/a bit": { ru: "немного", phoneticRu: "nemnogo" },
  "much/many/a lot": { ru: "много", phoneticRu: "mnogo" },
  "little/few": { ru: "мало", phoneticRu: "malo" },
  "enough/quite": { ru: "достаточно", phoneticRu: "dostatochno" },
  "tree": { ru: "дерево", phoneticRu: "derevo" },
  "grass": { ru: "трава", phoneticRu: "trava" },
  "leaf": { ru: "лист", phoneticRu: "list" },
  "branch": { ru: "ветка", phoneticRu: "vetka" },
  "root": { ru: "корень", phoneticRu: "koren'" },
  "seed": { ru: "семя", phoneticRu: "semya" },
  "stone/rock": { ru: "камень", phoneticRu: "kamen'" },
  "sand": { ru: "песок", phoneticRu: "pesok" },
  "fire": { ru: "огонь", phoneticRu: "ogon'" },
  "air": { ru: "воздух", phoneticRu: "vozdukh" },
  "wind": { ru: "ветер", phoneticRu: "veter" },
  "cloud": { ru: "облако", phoneticRu: "oblako" },
  "rain": { ru: "дождь", phoneticRu: "dozhd'" },
  "snow": { ru: "снег", phoneticRu: "sneg" },
  "ice": { ru: "лёд", phoneticRu: "lyod" },
  "sun": { ru: "солнце", phoneticRu: "solntse" },
  "moon": { ru: "луна", phoneticRu: "luna" },
  "star": { ru: "звезда", phoneticRu: "zvezda" },
  "fog": { ru: "туман", phoneticRu: "tuman" },
  "thunder": { ru: "гром", phoneticRu: "grom" },
  "lightning": { ru: "молния", phoneticRu: "molniya" },
  "rainbow": { ru: "радуга", phoneticRu: "raduga" },
  "bus": { ru: "автобус", phoneticRu: "avtobus" },
  "train": { ru: "поезд", phoneticRu: "poyezd" },
  "airplane": { ru: "самолёт", phoneticRu: "samolyot" },
  "ship": { ru: "корабль", phoneticRu: "korabl'" },
  "taxi": { ru: "такси", phoneticRu: "taksi" },
  "metro/subway": { ru: "метро", phoneticRu: "metro" },
  "tram": { ru: "трамвай", phoneticRu: "tramvay" },
  "motorcycle": { ru: "мотоцикл", phoneticRu: "mototsikl" },
  "ticket": { ru: "билет", phoneticRu: "bilet" },
  "passport": { ru: "паспорт", phoneticRu: "pasport" },
  "visa": { ru: "виза", phoneticRu: "viza" },
  "price": { ru: "цена", phoneticRu: "tsena" },
  "work/job": { ru: "работа", phoneticRu: "rabota" },
  "vacation/holiday": { ru: "отпуск", phoneticRu: "otpusk" },
  "health": { ru: "здоровье", phoneticRu: "zdorov'ye" },
  "illness/disease": { ru: "болезнь", phoneticRu: "bolezn'" },
  "pain": { ru: "боль", phoneticRu: "bol'" },
  "medicine": { ru: "лекарство", phoneticRu: "lekarstvo" },
  "life": { ru: "жизнь", phoneticRu: "zhizn'" },
  "death": { ru: "смерть", phoneticRu: "smert'" },
  "love": { ru: "любовь", phoneticRu: "lyubov'" },
  "happiness": { ru: "счастье", phoneticRu: "schast'ye" },
  "sadness/sorrow": { ru: "грусть", phoneticRu: "grust'" },
  "fear": { ru: "страх", phoneticRu: "strakh" },
  "anger": { ru: "гнев", phoneticRu: "gnev" },
  "joy": { ru: "радость", phoneticRu: "radost'" },
  "hope": { ru: "надежда", phoneticRu: "nadezhda" },
  "dream": { ru: "мечта", phoneticRu: "mechta" },
  "truth": { ru: "правда", phoneticRu: "pravda" },
  "lie/falsehood": { ru: "ложь", phoneticRu: "lozh'" },
  "freedom": { ru: "свобода", phoneticRu: "svoboda" },
  "peace": { ru: "мир", phoneticRu: "mir" },
  "war": { ru: "война", phoneticRu: "voyna" },
  "victory": { ru: "победа", phoneticRu: "pobeda" },
  "help": { ru: "помощь", phoneticRu: "pomoshch'" },
  "problem": { ru: "проблема", phoneticRu: "problema" },
  "answer": { ru: "ответ", phoneticRu: "otvet" },
  "question": { ru: "вопрос", phoneticRu: "vopros" },
  "idea": { ru: "идея", phoneticRu: "ideya" },
  "thought/opinion": { ru: "мысль/мнение", phoneticRu: "mysl'/mneniye" },
  "decision/solution": { ru: "решение", phoneticRu: "resheniye" },
  "plan": { ru: "план", phoneticRu: "plan" },
  "goal/aim": { ru: "цель", phoneticRu: "tsel'" },
  "reason/cause": { ru: "причина", phoneticRu: "prichina" },
  "result": { ru: "результат", phoneticRu: "rezul'tat" },
  "success": { ru: "успех", phoneticRu: "uspekh" },
  "mistake/error": { ru: "ошибка", phoneticRu: "oshibka" },
  "experience": { ru: "опыт", phoneticRu: "opyt" },
  "knowledge": { ru: "знание", phoneticRu: "znaniye" },
  "education": { ru: "образование", phoneticRu: "obrazovaniye" },
  "science": { ru: "наука", phoneticRu: "nauka" },
  "art": { ru: "искусство", phoneticRu: "iskusstvo" },
  "music": { ru: "музыка", phoneticRu: "muzyka" },
  "song": { ru: "песня", phoneticRu: "pesnya" },
  "film/movie": { ru: "фильм", phoneticRu: "fil'm" },
  "book": { ru: "книга", phoneticRu: "kniga" },
  "history/story": { ru: "история", phoneticRu: "istoriya" },
  "language": { ru: "язык", phoneticRu: "yazyk" },
  "word": { ru: "слово", phoneticRu: "slovo" },
  "sentence": { ru: "предложение", phoneticRu: "predlozheniye" },
  "number": { ru: "число", phoneticRu: "chislo" },
  "color": { ru: "цвет", phoneticRu: "tsvet" },
  "shape/form": { ru: "форма", phoneticRu: "forma" },
  "size": { ru: "размер", phoneticRu: "razmer" },
  "weight": { ru: "вес", phoneticRu: "ves" },
  "smell/scent": { ru: "запах", phoneticRu: "zapakh" },
  "taste": { ru: "вкус", phoneticRu: "vkus" },
  "sound": { ru: "звук", phoneticRu: "zvuk" },
  "light": { ru: "свет", phoneticRu: "svet" },
  "shadow": { ru: "тень", phoneticRu: "ten'" },
  "beginning": { ru: "начало", phoneticRu: "nachalo" },
  "end": { ru: "конец", phoneticRu: "konets" },
  "part": { ru: "часть", phoneticRu: "chast'" },
  "place": { ru: "место", phoneticRu: "mesto" },
  "name/title": { ru: "название", phoneticRu: "nazvaniye" },
  "first name": { ru: "имя", phoneticRu: "imya" },
  "surname/last name": { ru: "фамилия", phoneticRu: "familiya" },
  "address": { ru: "адрес", phoneticRu: "adres" },
  "number (identifier)": { ru: "номер", phoneticRu: "nomer" },
  "weather": { ru: "погода", phoneticRu: "pogoda" },
  "temperature": { ru: "температура", phoneticRu: "temperatura" },
  "hello/hi": { ru: "привет", phoneticRu: "privet" },
  "greetings/hello (formal)": { ru: "здравствуйте", phoneticRu: "zdravstvuyte" },
  "good morning": { ru: "доброе утро", phoneticRu: "dobroye utro" },
  "good afternoon/good day": { ru: "добрый день", phoneticRu: "dobryy den'" },
  "good evening": { ru: "добрый вечер", phoneticRu: "dobryy vecher" },
  "good night": { ru: "спокойной ночи", phoneticRu: "spokoynoy nochi" },
  "goodbye": { ru: "до свидания", phoneticRu: "do svidaniya" },
  "see you later": { ru: "до встречи", phoneticRu: "do vstrechi" },
  "bye (informal)": { ru: "пока", phoneticRu: "poka" },
  "thank you/thanks": { ru: "спасибо", phoneticRu: "spasibo" },
  "thank you very much": { ru: "большое спасибо", phoneticRu: "bol'shoye spasibo" },
  "please/you're welcome": { ru: "пожалуйста", phoneticRu: "pozhaluysta" },
  "excuse me/sorry (formal)": { ru: "извините", phoneticRu: "izvinite" },
  "I'm sorry/excuse me": { ru: "простите", phoneticRu: "prostite" },
  "you're welcome/don't mention it": { ru: "не за что", phoneticRu: "ne za chto" },
  "how are you": { ru: "как дела", phoneticRu: "kak dela" },
  "everything is fine": { ru: "всё хорошо", phoneticRu: "vsyo khorosho" },
  "my name is": { ru: "меня зовут", phoneticRu: "menya zovut" },
  "nice to meet you": { ru: "приятно познакомиться", phoneticRu: "priyatno poznakomit'sya" },
  "I don't understand": { ru: "я не понимаю", phoneticRu: "ya ne ponimayu" },
  "I understand": { ru: "я понимаю", phoneticRu: "ya ponimayu" },
  "please repeat": { ru: "повторите, пожалуйста", phoneticRu: "povtorite, pozhaluysta" },
  "how much does this cost": { ru: "сколько это стоит", phoneticRu: "skol'ko eto stoit" },
  "where is (located)": { ru: "где находится", phoneticRu: "gde nakhoditsya" },
  "I need": { ru: "мне нужно", phoneticRu: "mne nuzhno" },
  "I want": { ru: "я хочу", phoneticRu: "ya khochu" },
  "I love": { ru: "я люблю", phoneticRu: "ya lyublyu" },
  "glory to Ukraine": { ru: "слава Украине", phoneticRu: "slava Ukraine" },
  "glory to the heroes": { ru: "героям слава", phoneticRu: "geroyam slava" },
  "bon appetit/enjoy your meal": { ru: "приятного аппетита", phoneticRu: "priyatnogo appetita" },
  "cheers/let us be": { ru: "будем", phoneticRu: "budem" },
  "welcome": { ru: "добро пожаловать", phoneticRu: "dobro pozhalovat'" },
  "happy birthday": { ru: "с днём рождения", phoneticRu: "s dnyom rozhdeniya" },
  "happy New Year": { ru: "с Новым годом", phoneticRu: "s Novym godom" },
  "Merry Christmas": { ru: "с Рождеством", phoneticRu: "s Rozhdestvom" },
  "unfortunately": { ru: "к сожалению", phoneticRu: "k sozhalenyu" },
  "of course/certainly": { ru: "конечно", phoneticRu: "konechno" },
  "I agree": { ru: "я согласен", phoneticRu: "ya soglasen" },
  "help (imperative)": { ru: "помогите", phoneticRu: "pomogite" },
  "Ukraine": { ru: "Украина", phoneticRu: "Ukraina" },
  "Kyiv": { ru: "Киев", phoneticRu: "Kiyev" },
  "Lviv": { ru: "Львов", phoneticRu: "L'vov" },
  "Odesa": { ru: "Одесса", phoneticRu: "Odessa" },
  "Kharkiv": { ru: "Харьков", phoneticRu: "Khar'kov" },
  "Dnipro": { ru: "Днепр", phoneticRu: "Dnepr" },
  "Zaporizhzhia": { ru: "Запорожье", phoneticRu: "Zaporozh'ye" },
  "Poltava": { ru: "Полтава", phoneticRu: "Poltava" },
  "Chernihiv": { ru: "Чернигов", phoneticRu: "Chernigov" },
  "Vinnytsia": { ru: "Винница", phoneticRu: "Vinnitsa" },
  "Ternopil": { ru: "Тернополь", phoneticRu: "Ternopol'" },
  "Ivano-Frankivsk": { ru: "Ивано-Франковск", phoneticRu: "Ivano-Frankovsk" },
  "Uzhhorod": { ru: "Ужгород", phoneticRu: "Uzhgorod" },
  "Chernivtsi": { ru: "Черновцы", phoneticRu: "Chernovtsy" },
  "Kherson": { ru: "Херсон", phoneticRu: "Kherson" },
  "Mariupol": { ru: "Мариуполь", phoneticRu: "Mariupol'" },
  "internet": { ru: "интернет", phoneticRu: "internet" },
  "email": { ru: "электронная почта", phoneticRu: "elektronnaya pochta" },
  "password": { ru: "пароль", phoneticRu: "parol'" },
  "screen": { ru: "экран", phoneticRu: "ekran" },
  "keyboard": { ru: "клавиатура", phoneticRu: "klaviatura" },
  "mouse (computer)": { ru: "мышка", phoneticRu: "myshka" },
  "printer": { ru: "принтер", phoneticRu: "printer" },
  "program/application": { ru: "программа", phoneticRu: "programma" },
  "website": { ru: "сайт", phoneticRu: "sayt" },
  "message": { ru: "сообщение", phoneticRu: "soobshcheniye" },
  "phone call/ring": { ru: "звонок", phoneticRu: "zvonok" },
  "photo": { ru: "фото", phoneticRu: "foto" },
  "video": { ru: "видео", phoneticRu: "video" },
  "battery": { ru: "батарея", phoneticRu: "batareya" },
  "charger": { ru: "зарядка", phoneticRu: "zaryadka" },
  // RU-only entries that need UK translations
  "to study/to teach": { ru: "учить", phoneticRu: "uchit'" },
  "to begin": { ru: "начинать", phoneticRu: "nachinat'" },
  "to remember/recall": { ru: "вспоминать", phoneticRu: "vspominat'" },
  "to receive": { ru: "получать", phoneticRu: "poluchat'" },
  "to draw": { ru: "рисовать", phoneticRu: "risovat'" },
  "to be afraid": { ru: "бояться", phoneticRu: "boyat'sya" },
  "man": { ru: "мужчина", phoneticRu: "muzhchina" },
  "woman": { ru: "женщина", phoneticRu: "zhenshchina" },
  "boy": { ru: "мальчик", phoneticRu: "mal'chik" },
  "girl": { ru: "девочка", phoneticRu: "devochka" },
  "student": { ru: "студент", phoneticRu: "student" },
  "family": { ru: "семья", phoneticRu: "sem'ya" },
  "mother": { ru: "мать", phoneticRu: "mat'" },
  "boss/chief": { ru: "начальник", phoneticRu: "nachal'nik" },
  "house/home": { ru: "дом", phoneticRu: "dom" },
  "car": { ru: "машина", phoneticRu: "mashina" },
  "phone": { ru: "телефон", phoneticRu: "telefon" },
  "letter": { ru: "письмо", phoneticRu: "pis'mo" },
  "good": { ru: "хороший", phoneticRu: "khoroshiy" },
  "beautiful": { ru: "красивый", phoneticRu: "krasivyy" },
  "short": { ru: "короткий", phoneticRu: "korotkiy" },
  "heavy": { ru: "тяжёлый", phoneticRu: "tyazhyolyy" },
  "low/short": { ru: "низкий", phoneticRu: "nizkiy" },
  "clean/pure": { ru: "чистый", phoneticRu: "chistyy" },
  "cheerful/merry": { ru: "весёлый", phoneticRu: "vesyolyy" },
  "kind/good-natured": { ru: "добрый", phoneticRu: "dobryy" },
  "hard/firm": { ru: "твёрдый", phoneticRu: "tvyordyy" },
  "quiet/calm": { ru: "тихий", phoneticRu: "tikhiy" },
  "complex/difficult": { ru: "сложный", phoneticRu: "slozhnyy" },
};

// Now build the trilingual output
const usedEnKeys = new Set();
const outputWords = [];

// Process all UK entries
for (const w of ukData.words) {
  const ruMatch = ruByEn[w.en] || manualRu[w.en];

  const entry = {
    uk: w.uk,
    ru: ruMatch ? ruMatch.ru : "???",
    en: w.en,
    phoneticUk: w.phonetic,
    phoneticRu: ruMatch ? ruMatch.phoneticRu : "???",
    category: w.category
  };

  if (entry.ru === "???") {
    console.error("MISSING RU for:", w.en);
  }

  outputWords.push(entry);
  usedEnKeys.add(w.en);
}

// Add RU-only entries
for (const w of ruData.words) {
  if (!usedEnKeys.has(w.en)) {
    // Need to generate UK translations for these
    const ukTranslations = {
      "to study/to teach": { uk: "вчити", phoneticUk: "vchyty" },
      "to begin": { uk: "починати", phoneticUk: "pochynaty" },
      "to remember/recall": { uk: "згадувати", phoneticUk: "zhaduvaty" },
      "to receive": { uk: "отримувати", phoneticUk: "otrymuvaty" },
      "to draw": { uk: "малювати", phoneticUk: "malyuvaty" },
      "to be afraid": { uk: "боятися", phoneticUk: "boyatysya" },
      "man": { uk: "чоловік", phoneticUk: "cholovik" },
      "woman": { uk: "жінка", phoneticUk: "zhinka" },
      "boy": { uk: "хлопчик", phoneticUk: "khlopchyk" },
      "girl": { uk: "дівчинка", phoneticUk: "divchynka" },
      "student": { uk: "студент", phoneticUk: "student" },
      "family": { uk: "сім'я", phoneticUk: "simya" },
      "mother": { uk: "мати", phoneticUk: "maty" },
      "boss/chief": { uk: "начальник", phoneticUk: "nachalnyk" },
      "house/home": { uk: "дім", phoneticUk: "dim" },
      "car": { uk: "машина", phoneticUk: "mashyna" },
      "phone": { uk: "телефон", phoneticUk: "telefon" },
      "letter": { uk: "лист", phoneticUk: "lyst" },
      "good": { uk: "хороший", phoneticUk: "khoroshyi" },
      "beautiful": { uk: "красивий", phoneticUk: "krasyvyi" },
      "short": { uk: "короткий", phoneticUk: "korotkyi" },
      "heavy": { uk: "важкий", phoneticUk: "vazhkyi" },
      "low/short": { uk: "низький", phoneticUk: "nyzkyi" },
      "clean/pure": { uk: "чистий", phoneticUk: "chystyi" },
      "cheerful/merry": { uk: "веселий", phoneticUk: "veselyi" },
      "kind/good-natured": { uk: "добрий", phoneticUk: "dobryi" },
      "hard/firm": { uk: "твердий", phoneticUk: "tverdyi" },
      "quiet/calm": { uk: "тихий", phoneticUk: "tykhyi" },
      "complex/difficult": { uk: "складний", phoneticUk: "skladnyi" },
    };

    const ukMatch = ukTranslations[w.en];
    if (ukMatch) {
      outputWords.push({
        uk: ukMatch.uk,
        ru: w.ru,
        en: w.en,
        phoneticUk: ukMatch.phoneticUk,
        phoneticRu: w.phonetic,
        category: w.category
      });
    } else {
      console.error("MISSING UK for RU-only:", w.en);
    }
  }
}

console.log("Total output words:", outputWords.length);

// Check for any "???" entries
const missing = outputWords.filter(w => w.ru === "???" || w.phoneticRu === "???");
if (missing.length > 0) {
  console.error("MISSING entries:", missing.length);
  for (const m of missing) console.error("  ", m.en);
}

// Write output
const output = { words: outputWords };
fs.writeFileSync(ukPath, JSON.stringify(output, null, 2), 'utf8');
console.log("Written to:", ukPath);
