const fs = require('fs');

const ukPath = 'C:/Users/michael/Desktop/ukrainian typing game/src/data/vocabulary/comprehensive-dictionary-ext.json';
const ruPath = 'C:/Users/michael/Desktop/ukrainian typing game/src/data/ru/vocabulary/comprehensive-dictionary-ext.json';

const ukData = JSON.parse(fs.readFileSync(ukPath, 'utf8'));
const ruData = JSON.parse(fs.readFileSync(ruPath, 'utf8'));

const ruByEn = {};
for (const w of ruData.words) {
  ruByEn[w.en] = { ru: w.ru, phoneticRu: w.phonetic };
}

// Manual Russian translations for ALL entries that won't match
const manualRu = {
  // Verbs
  "to forgive": { ru: "прощать", phoneticRu: "proshchat'" },
  "to allow/to permit": { ru: "разрешать", phoneticRu: "razreshat'" },
  "to forbid": { ru: "запрещать", phoneticRu: "zapreshchat'" },
  "to agree": { ru: "соглашаться", phoneticRu: "soglashat'sya" },
  "to refuse": { ru: "отказываться", phoneticRu: "otkazyvat'sya" },
  "to suggest/to offer": { ru: "предлагать", phoneticRu: "predlagat'" },
  "to complain": { ru: "жаловаться", phoneticRu: "zhalovat'sya" },
  "to praise": { ru: "хвалить", phoneticRu: "khvalit'" },
  "to criticize": { ru: "критиковать", phoneticRu: "kritikovat'" },
  "to quarrel": { ru: "ссориться", phoneticRu: "ssorit'sya" },
  "to be silent": { ru: "молчать", phoneticRu: "molchat'" },
  "to recall/to mention": { ru: "вспоминать", phoneticRu: "vspominat'" },
  "to imagine": { ru: "представлять", phoneticRu: "predstavlyat'" },
  "to compare": { ru: "сравнивать", phoneticRu: "sravnivat'" },
  "to check/to verify": { ru: "проверять", phoneticRu: "proveryat'" },
  "to correct/to fix": { ru: "исправлять", phoneticRu: "ispravlyat'" },
  "to add": { ru: "добавлять", phoneticRu: "dobavlyat'" },
  "to delete/to remove": { ru: "удалять", phoneticRu: "udalyat'" },
  "to create": { ru: "создавать", phoneticRu: "sozdavat'" },
  "to destroy": { ru: "уничтожать", phoneticRu: "unichtozhat'" },
  "to repair": { ru: "ремонтировать", phoneticRu: "remontirovat'" },
  "to order": { ru: "заказывать", phoneticRu: "zakazyvat'" },
  "to deliver": { ru: "доставлять", phoneticRu: "dostavlyat'" },
  "to pack": { ru: "упаковывать", phoneticRu: "upakovyvat'" },
  "to unpack": { ru: "распаковывать", phoneticRu: "raspakovyvat'" },
  "to sign": { ru: "подписывать", phoneticRu: "podpisyvat'" },
  "to print/to type": { ru: "печатать", phoneticRu: "pechatat'" },
  "to copy": { ru: "копировать", phoneticRu: "kopirovat'" },
  "to measure": { ru: "измерять", phoneticRu: "izmeryat'" },
  "to count/to calculate": { ru: "считать", phoneticRu: "schitat'" },
  "to collect/to gather": { ru: "собирать", phoneticRu: "sobirat'" },
  "to divide/to separate": { ru: "разделять", phoneticRu: "razdelyat'" },
  "to connect/to join": { ru: "соединять", phoneticRu: "soyedinyat'" },
  "to mix": { ru: "смешивать", phoneticRu: "smeshivat'" },
  "to pour": { ru: "наливать", phoneticRu: "nalivat'" },
  "to sprinkle/to pour (dry)": { ru: "сыпать", phoneticRu: "sypat'" },
  "to fry": { ru: "жарить", phoneticRu: "zharit'" },
  "to boil/to cook": { ru: "варить", phoneticRu: "varit'" },
  "to bake": { ru: "печь", phoneticRu: "pech'" },
  "to heat up": { ru: "нагревать", phoneticRu: "nagrevat'" },
  "to cool down": { ru: "охлаждать", phoneticRu: "okhlazhat'" },
  "to freeze": { ru: "замораживать", phoneticRu: "zamorazhivat'" },
  "to melt": { ru: "таять", phoneticRu: "tayat'" },
  "to dry": { ru: "сушить", phoneticRu: "sushit'" },
  "to wet/to soak": { ru: "мочить", phoneticRu: "mochit'" },
  "to iron": { ru: "гладить", phoneticRu: "gladit'" },
  "to sew": { ru: "шить", phoneticRu: "shit'" },
  "to knit/to tie": { ru: "вязать", phoneticRu: "vyazat'" },
  "to do laundry": { ru: "стирать", phoneticRu: "stirat'" },
  "to vacuum": { ru: "пылесосить", phoneticRu: "pylesosit'" },
  "to sweep": { ru: "подметать", phoneticRu: "podmetat'" },
  "to wipe": { ru: "вытирать", phoneticRu: "vytirat'" },
  "to polish": { ru: "полировать", phoneticRu: "polirovat'" },
  "to plant": { ru: "сажать", phoneticRu: "sazhat'" },
  "to water (plants)": { ru: "поливать", phoneticRu: "polivat'" },
  "to dig": { ru: "копать", phoneticRu: "kopat'" },
  "to cut (hair)/to mow": { ru: "стричь", phoneticRu: "strich'" },
  "to stroll/to hang out": { ru: "гулять", phoneticRu: "gulyat'" },
  "to rest/to relax": { ru: "отдыхать", phoneticRu: "otdykhat'" },
  "to celebrate": { ru: "праздновать", phoneticRu: "prazdnovat'" },
  "to photograph": { ru: "фотографировать", phoneticRu: "fotografirovat'" },
  "to draw": { ru: "рисовать", phoneticRu: "risovat'" },
  "to type": { ru: "печатать", phoneticRu: "pechatat'" },
  "to vote": { ru: "голосовать", phoneticRu: "golosovat'" },
  "to manage/to drive": { ru: "управлять", phoneticRu: "upravlyat'" },
  "to organize": { ru: "организовывать", phoneticRu: "organizovyvat'" },
  "to plan": { ru: "планировать", phoneticRu: "planirovat'" },
  "to control": { ru: "контролировать", phoneticRu: "kontrolirovat'" },
  "to defend/to protect": { ru: "защищать", phoneticRu: "zashchishchat'" },
  "to attack": { ru: "атаковать", phoneticRu: "atakovat'" },
  "to win/to defeat": { ru: "побеждать", phoneticRu: "pobezhdat'" },
  "to lose (a game)": { ru: "проигрывать", phoneticRu: "proigryvat'" },
  "to train/to practice": { ru: "тренироваться", phoneticRu: "trenirovat'sya" },
  "to compete": { ru: "соревноваться", phoneticRu: "sorevnovat'sya" },
  "to worry": { ru: "волноваться", phoneticRu: "volnovat'sya" },
  "to envy": { ru: "завидовать", phoneticRu: "zavidovat'" },
  "to hate": { ru: "ненавидеть", phoneticRu: "nenavidet'" },
  "to trust": { ru: "доверять", phoneticRu: "doveryat'" },
  "to suspect": { ru: "подозревать", phoneticRu: "podozrevat'" },
  "to be surprised": { ru: "удивляться", phoneticRu: "udivlyat'sya" },
  "to regret": { ru: "жалеть", phoneticRu: "zhalet'" },
  "to be proud": { ru: "гордиться", phoneticRu: "gordit'sya" },
  "to be ashamed": { ru: "стыдиться", phoneticRu: "stydit'sya" },
  "to be nervous": { ru: "нервничать", phoneticRu: "nervnichat'" },
  "to rejoice": { ru: "радоваться", phoneticRu: "radovat'sya" },
  "to suffer": { ru: "страдать", phoneticRu: "stradat'" },
  "to risk": { ru: "рисковать", phoneticRu: "riskovat'" },
  "to rescue/to save": { ru: "спасать", phoneticRu: "spasat'" },
  "to escape/to flee": { ru: "убегать", phoneticRu: "ubegat'" },
  "to pursue/to chase": { ru: "преследовать", phoneticRu: "presledovat'" },
  "to follow/to watch": { ru: "следить", phoneticRu: "sledit'" },
  "to hide (oneself)": { ru: "прятаться", phoneticRu: "pryatat'sya" },
  "to approach": { ru: "приближаться", phoneticRu: "priblizhat'sya" },
  "to move away": { ru: "удаляться", phoneticRu: "udalyat'sya" },
  "to turn around/to rotate": { ru: "вращаться", phoneticRu: "vrashchat'sya" },
  "to lean/to bend": { ru: "наклоняться", phoneticRu: "naklonyat'sya" },
  "to jump": { ru: "прыгать", phoneticRu: "prygat'" },
  "to crawl": { ru: "ползти", phoneticRu: "polzti" },
  "to slide/to skate": { ru: "скользить", phoneticRu: "skol'zit'" },
  "to climb": { ru: "лазить", phoneticRu: "lazit'" },
  "to rock/to swing": { ru: "качать", phoneticRu: "kachat'" },
  "to spin/to twist": { ru: "крутить", phoneticRu: "krutit'" },
  "to press/to squeeze": { ru: "давить", phoneticRu: "davit'" },
  "to beat/to hit": { ru: "бить", phoneticRu: "bit'" },
  "to knock": { ru: "стучать", phoneticRu: "stuchat'" },
  "to strike": { ru: "ударить", phoneticRu: "udarit'" },
  "to stroke/to pet": { ru: "гладить", phoneticRu: "gladit'" },
  "to attach/to hook": { ru: "прицеплять", phoneticRu: "pritseplyat'" },
  "to shut/to lock": { ru: "запирать", phoneticRu: "zapirat'" },
  "to turn on": { ru: "включать", phoneticRu: "vklyuchat'" },
  "to turn off": { ru: "выключать", phoneticRu: "vyklyuchat'" },
  "to press (a button)": { ru: "нажимать", phoneticRu: "nazhimat'" },
  "to insert": { ru: "вставлять", phoneticRu: "vstavlyat'" },
  "to take out/to extract": { ru: "вынимать", phoneticRu: "vynimat'" },
  "to wrap": { ru: "заворачивать", phoneticRu: "zavorachivat'" },
  "to unwrap": { ru: "разворачивать", phoneticRu: "razvorachivat'" },
  "to fold/to compose": { ru: "складывать", phoneticRu: "skladyvat'" },
  "to unfold/to arrange": { ru: "раскладывать", phoneticRu: "raskladyvat'" },
  "to fill": { ru: "заполнять", phoneticRu: "zapolnyat'" },
  "to empty": { ru: "опустошать", phoneticRu: "opustoshat'" },
  "to transfer/to carry over": { ru: "переносить", phoneticRu: "perenosit'" },
  "to throw over/to overturn": { ru: "перебрасывать", phoneticRu: "perebrasyvat'" },
  "to smell/to sniff": { ru: "нюхать", phoneticRu: "nyukhat'" },
  "to taste/to try food": { ru: "пробовать", phoneticRu: "probovat'" },
  "to swallow": { ru: "глотать", phoneticRu: "glotat'" },
  "to chew": { ru: "жевать", phoneticRu: "zhevat'" },
  "to bite": { ru: "кусать", phoneticRu: "kusat'" },
  "to breathe": { ru: "дышать", phoneticRu: "dyshat'" },
  "to cough": { ru: "кашлять", phoneticRu: "kashlyat'" },
  "to sneeze": { ru: "чихать", phoneticRu: "chikhat'" },
  "to yawn": { ru: "зевать", phoneticRu: "zevat'" },
  "to vomit": { ru: "рвать", phoneticRu: "rvat'" },
  "to bleed": { ru: "кровоточить", phoneticRu: "krovotochit'" },
  "to treat/to cure": { ru: "лечить", phoneticRu: "lechit'" },
  "to recover": { ru: "выздоравливать", phoneticRu: "vyzdoravlivat'" },
  "to infect": { ru: "заражать", phoneticRu: "zarazhat'" },
  "to vaccinate": { ru: "вакцинировать", phoneticRu: "vaktsinirovat'" },
  "to operate (surgery)": { ru: "оперировать", phoneticRu: "operirovat'" },
  "to bandage": { ru: "бинтовать", phoneticRu: "bintovat'" },
  "to hire": { ru: "нанимать", phoneticRu: "nanimat'" },
  "to fire/to dismiss": { ru: "увольнять", phoneticRu: "uvol'nyat'" },
  "to earn": { ru: "зарабатывать", phoneticRu: "zarabatyvat'" },
  "to spend": { ru: "тратить", phoneticRu: "tratit'" },
  "to borrow/to lend": { ru: "занимать/одалживать", phoneticRu: "zanimat'/odalzhivat'" },
  "to invest": { ru: "инвестировать", phoneticRu: "investirovat'" },
  "to export": { ru: "экспортировать", phoneticRu: "eksportirovat'" },
  "to import": { ru: "импортировать", phoneticRu: "importirovat'" },
  "to advertise": { ru: "рекламировать", phoneticRu: "reklamirovat'" },
  "to trade": { ru: "торговать", phoneticRu: "torgovat'" },
  "to serve/to service": { ru: "обслуживать", phoneticRu: "obsluzhivat'" },
  "to download/to load": { ru: "загружать", phoneticRu: "zagruzhat'" },
  "to update": { ru: "обновлять", phoneticRu: "obnovlyat'" },
  "to install": { ru: "устанавливать", phoneticRu: "ustanavlivat'" },
  "to uninstall/to delete": { ru: "удалять", phoneticRu: "udalyat'" },
  "to save/to store": { ru: "сохранять", phoneticRu: "sokhranit'" },
  "to send (mail/email)": { ru: "отправлять", phoneticRu: "otpravlyat'" },
  "to receive": { ru: "получать", phoneticRu: "poluchat'" },
  "to connect/to plug in": { ru: "подключать", phoneticRu: "podklyuchat'" },
  "to disconnect": { ru: "отключать", phoneticRu: "otklyuchat'" },
  "to program/to code": { ru: "программировать", phoneticRu: "programmirovat'" },
  "to teach/to educate": { ru: "обучать", phoneticRu: "obuchat'" },
  "to examine/to test": { ru: "экзаменовать", phoneticRu: "ekzamenovat'" },
  "to evaluate/to grade": { ru: "оценивать", phoneticRu: "otsenivat'" },
  "to research/to explore": { ru: "исследовать", phoneticRu: "issledovat'" },
  "to analyze": { ru: "анализировать", phoneticRu: "analizirovat'" },
  "to publish": { ru: "публиковать", phoneticRu: "publikovat'" },
  "to edit": { ru: "редактировать", phoneticRu: "redaktirovat'" },
  "to translate": { ru: "переводить", phoneticRu: "perevodit'" },
  "to interpret": { ru: "толковать", phoneticRu: "tolkovat'" },
  "to pronounce": { ru: "произносить", phoneticRu: "proiznosit'" },
  "to emphasize/to stress": { ru: "подчёркивать", phoneticRu: "podchyorkivat'" },
  "to quote": { ru: "цитировать", phoneticRu: "tsitirovat'" },
  "to register": { ru: "регистрировать", phoneticRu: "registrirovat'" },
  "to reserve/to book": { ru: "бронировать", phoneticRu: "bronirovat'" },
  "to cancel": { ru: "отменять", phoneticRu: "otmenyat'" },
  "to postpone/to reschedule": { ru: "переносить", phoneticRu: "perenosit'" },
  "to confirm": { ru: "подтверждать", phoneticRu: "podtverzhdat'" },
  "to reject/to decline": { ru: "отклонять", phoneticRu: "otklonyat'" },
  "to recommend": { ru: "рекомендовать", phoneticRu: "rekomendovat'" },
  "to guarantee": { ru: "гарантировать", phoneticRu: "garantirovat'" },
  "to embrace/to hold": { ru: "обнимать", phoneticRu: "obnimat'" },
  "to greet each other": { ru: "здороваться", phoneticRu: "zdorovat'sya" },
  "to get acquainted": { ru: "знакомиться", phoneticRu: "znakomit'sya" },
  "to be late": { ru: "опаздывать", phoneticRu: "opazdyvat'" },
  "to hurry": { ru: "спешить", phoneticRu: "speshit'" },
  "to feed": { ru: "кормить", phoneticRu: "kormit'" },
  "to take care of": { ru: "ухаживать", phoneticRu: "ukhazhivat'" },
  "to raise/to bring up": { ru: "воспитывать", phoneticRu: "vospityvat'" },
  "to punish": { ru: "наказывать", phoneticRu: "nakazyvat'" },
  "to reward": { ru: "награждать", phoneticRu: "nagrazhdat'" },
  "to get married": { ru: "жениться/выходить замуж", phoneticRu: "zhenit'sya/vykhodit' zamuzh" },
  "to divorce": { ru: "разводиться", phoneticRu: "razvodit'sya" },
  "to give birth": { ru: "рожать", phoneticRu: "rozhat'" },
  "to age/to grow old": { ru: "стареть", phoneticRu: "staret'" },
  "to lose weight": { ru: "худеть", phoneticRu: "khudet'" },
  "to gain weight": { ru: "толстеть", phoneticRu: "tolstet'" },
  "to blush": { ru: "краснеть", phoneticRu: "krasnet'" },
  "to turn pale": { ru: "бледнеть", phoneticRu: "blednet'" },
  "to sweat": { ru: "потеть", phoneticRu: "potet'" },
  "to tremble/to shiver": { ru: "дрожать", phoneticRu: "drozhat'" },
  "to be cold/to freeze": { ru: "мёрзнуть", phoneticRu: "myorznut'" },
  "to warm oneself": { ru: "греться", phoneticRu: "gret'sya" },
  // Animals
  "dog": { ru: "собака", phoneticRu: "sobaka" },
  "cat": { ru: "кот", phoneticRu: "kot" },
  "cat (female)": { ru: "кошка", phoneticRu: "koshka" },
  "cow": { ru: "корова", phoneticRu: "korova" },
  "bull": { ru: "бык", phoneticRu: "byk" },
  "horse": { ru: "лошадь", phoneticRu: "loshad'" },
  "mare": { ru: "кобыла", phoneticRu: "kobyla" },
  "pig": { ru: "свинья", phoneticRu: "svin'ya" },
  "sheep": { ru: "овца", phoneticRu: "ovtsa" },
  "goat": { ru: "коза", phoneticRu: "koza" },
  "chicken/hen": { ru: "курица", phoneticRu: "kuritsa" },
  "rooster": { ru: "петух", phoneticRu: "petukh" },
  "duck": { ru: "утка", phoneticRu: "utka" },
  "goose": { ru: "гусь", phoneticRu: "gus'" },
  "turkey": { ru: "индюк", phoneticRu: "indyuk" },
  "rabbit": { ru: "кролик", phoneticRu: "krolik" },
  "wolf": { ru: "волк", phoneticRu: "volk" },
  "fox": { ru: "лиса", phoneticRu: "lisa" },
  "bear": { ru: "медведь", phoneticRu: "medved'" },
  "deer": { ru: "олень", phoneticRu: "olen'" },
  "moose/elk": { ru: "лось", phoneticRu: "los'" },
  "hare": { ru: "заяц", phoneticRu: "zayats" },
  "squirrel": { ru: "белка", phoneticRu: "belka" },
  "hedgehog": { ru: "ёж", phoneticRu: "yozh" },
  "mouse": { ru: "мышь", phoneticRu: "mysh'" },
  "rat": { ru: "крыса", phoneticRu: "krysa" },
  "bat": { ru: "летучая мышь", phoneticRu: "letuchaya mysh'" },
  "tiger": { ru: "тигр", phoneticRu: "tigr" },
  "lion": { ru: "лев", phoneticRu: "lev" },
  "elephant": { ru: "слон", phoneticRu: "slon" },
  "giraffe": { ru: "жираф", phoneticRu: "zhiraf" },
  "zebra": { ru: "зебра", phoneticRu: "zebra" },
  "monkey/ape": { ru: "обезьяна", phoneticRu: "obez'yana" },
  "camel": { ru: "верблюд", phoneticRu: "verblyud" },
  "rhinoceros": { ru: "носорог", phoneticRu: "nosorog" },
  "hippopotamus": { ru: "бегемот", phoneticRu: "begemot" },
  "crocodile": { ru: "крокодил", phoneticRu: "krokodil" },
  "snake": { ru: "змея", phoneticRu: "zmeya" },
  "lizard": { ru: "ящерица", phoneticRu: "yashcheritsa" },
  "turtle/tortoise": { ru: "черепаха", phoneticRu: "cherepakha" },
  "frog": { ru: "лягушка", phoneticRu: "lyagushka" },
  "dolphin": { ru: "дельфин", phoneticRu: "del'fin" },
  "whale": { ru: "кит", phoneticRu: "kit" },
  "shark": { ru: "акула", phoneticRu: "akula" },
  "octopus": { ru: "осьминог", phoneticRu: "os'minog" },
  "crab": { ru: "краб", phoneticRu: "krab" },
  "shrimp": { ru: "креветка", phoneticRu: "krevetka" },
  "oyster": { ru: "устрица", phoneticRu: "ustritsa" },
  "jellyfish": { ru: "медуза", phoneticRu: "meduza" },
  "starfish": { ru: "морская звезда", phoneticRu: "morskaya zvezda" },
  "eagle": { ru: "орёл", phoneticRu: "oryol" },
  "falcon": { ru: "сокол", phoneticRu: "sokol" },
  "owl": { ru: "сова", phoneticRu: "sova" },
  "crow": { ru: "ворона", phoneticRu: "vorona" },
  "sparrow": { ru: "воробей", phoneticRu: "vorobey" },
  "pigeon/dove": { ru: "голубь", phoneticRu: "golub'" },
  "swan": { ru: "лебедь", phoneticRu: "lebed'" },
  "parrot": { ru: "попугай", phoneticRu: "popugay" },
  "penguin": { ru: "пингвин", phoneticRu: "pingvin" },
  "stork": { ru: "аист", phoneticRu: "aist" },
  "seagull": { ru: "чайка", phoneticRu: "chayka" },
  "pelican": { ru: "пеликан", phoneticRu: "pelikan" },
  "woodpecker": { ru: "дятел", phoneticRu: "dyatel" },
  "swallow (bird)": { ru: "ласточка", phoneticRu: "lastochka" },
  "nightingale": { ru: "соловей", phoneticRu: "solovey" },
  "bee": { ru: "пчела", phoneticRu: "pchela" },
  "wasp": { ru: "оса", phoneticRu: "osa" },
  "fly": { ru: "муха", phoneticRu: "mukha" },
  "mosquito": { ru: "комар", phoneticRu: "komar" },
  "butterfly": { ru: "бабочка", phoneticRu: "babochka" },
  "ant": { ru: "муравей", phoneticRu: "muravey" },
  "spider": { ru: "паук", phoneticRu: "pauk" },
  "beetle": { ru: "жук", phoneticRu: "zhuk" },
  "worm": { ru: "червь", phoneticRu: "cherv'" },
  "snail": { ru: "улитка", phoneticRu: "ulitka" },
  "dragonfly": { ru: "стрекоза", phoneticRu: "strekoza" },
  "grasshopper": { ru: "кузнечик", phoneticRu: "kuznechik" },
  "cricket": { ru: "сверчок", phoneticRu: "sverchok" },
  "animal": { ru: "животное", phoneticRu: "zhivotnoye" },
  "beast/wild animal": { ru: "зверь", phoneticRu: "zver'" },
  "bird": { ru: "птица", phoneticRu: "ptitsa" },
  "insect": { ru: "насекомое", phoneticRu: "nasekomoye" },
  "tail": { ru: "хвост", phoneticRu: "khvost" },
  "wing": { ru: "крыло", phoneticRu: "krylo" },
  "paw": { ru: "лапа", phoneticRu: "lapa" },
  "beak": { ru: "клюв", phoneticRu: "klyuv" },
  "feather": { ru: "перо", phoneticRu: "pero" },
  "fur/wool": { ru: "шерсть", phoneticRu: "sherst'" },
  "scales": { ru: "чешуя", phoneticRu: "cheshuya" },
  "hoof": { ru: "копыто", phoneticRu: "kopyto" },
  "horn": { ru: "рог", phoneticRu: "rog" },
  "fang/tusk": { ru: "клык", phoneticRu: "klyk" },
  "nest": { ru: "гнездо", phoneticRu: "gnezdo" },
  "burrow/den": { ru: "нора", phoneticRu: "nora" },
  "cage/cell": { ru: "клетка", phoneticRu: "kletka" },
  "aquarium": { ru: "аквариум", phoneticRu: "akvarium" },
  "zoo": { ru: "зоопарк", phoneticRu: "zoopark" },
  // Colors
  "red": { ru: "красный", phoneticRu: "krasnyy" },
  "blue": { ru: "синий", phoneticRu: "siniy" },
  "green": { ru: "зелёный", phoneticRu: "zelyonyy" },
  "yellow": { ru: "жёлтый", phoneticRu: "zhyoltyy" },
  "white": { ru: "белый", phoneticRu: "belyy" },
  "black": { ru: "чёрный", phoneticRu: "chyornyy" },
  "gray": { ru: "серый", phoneticRu: "seryy" },
  "brown": { ru: "коричневый", phoneticRu: "korichnevyy" },
  "pink": { ru: "розовый", phoneticRu: "rozovyy" },
  "purple/violet": { ru: "фиолетовый", phoneticRu: "fioletovyy" },
  "orange (color)": { ru: "оранжевый", phoneticRu: "oranzhevyy" },
  "light blue": { ru: "голубой", phoneticRu: "goluboy" },
  "beige": { ru: "бежевый", phoneticRu: "bezhevyy" },
  "burgundy/maroon": { ru: "бордовый", phoneticRu: "bordovyy" },
  "gold/golden": { ru: "золотой", phoneticRu: "zolotoy" },
  "silver": { ru: "серебряный", phoneticRu: "serebryanyy" },
  "turquoise": { ru: "бирюзовый", phoneticRu: "biryuzovyy" },
  "crimson": { ru: "малиновый", phoneticRu: "malinovyy" },
  "cream": { ru: "кремовый", phoneticRu: "kremovyy" },
  "lime green": { ru: "салатовый", phoneticRu: "salatovyy" },
  "bronze": { ru: "бронзовый", phoneticRu: "bronzovyy" },
  "bright/vivid": { ru: "яркий", phoneticRu: "yarkiy" },
  "dull/dim": { ru: "тусклый", phoneticRu: "tusklyy" },
  "transparent": { ru: "прозрачный", phoneticRu: "prozrachnyy" },
  // Weather
  "frost": { ru: "мороз", phoneticRu: "moroz" },
  "heat wave": { ru: "жара", phoneticRu: "zhara" },
  "storm": { ru: "шторм", phoneticRu: "shtorm" },
  "hurricane": { ru: "ураган", phoneticRu: "uragan" },
  "tornado": { ru: "торнадо", phoneticRu: "tornado" },
  "hail": { ru: "град", phoneticRu: "grad" },
  "dew": { ru: "роса", phoneticRu: "rosa" },
  "hoarfrost": { ru: "иней", phoneticRu: "iney" },
  "black ice": { ru: "гололёд", phoneticRu: "gololyod" },
  "flood": { ru: "наводнение", phoneticRu: "navodneniye" },
  "drought": { ru: "засуха", phoneticRu: "zasukha" },
  "cloudy": { ru: "облачно", phoneticRu: "oblachno" },
  "sunny": { ru: "солнечно", phoneticRu: "solnechno" },
  "windy": { ru: "ветрено", phoneticRu: "vetreno" },
  "it is raining": { ru: "идёт дождь", phoneticRu: "idyot dozhd'" },
  "snowfall": { ru: "снегопад", phoneticRu: "snegopad" },
  "blizzard": { ru: "метель", phoneticRu: "metel'" },
  "downpour/heavy rain": { ru: "ливень", phoneticRu: "liven'" },
  "foggy": { ru: "туманно", phoneticRu: "tumanno" },
  "clear (weather)": { ru: "ясно", phoneticRu: "yasno" },
  "chilly": { ru: "прохладно", phoneticRu: "prokhladno" },
  "frosty": { ru: "морозно", phoneticRu: "morozno" },
  "weather forecast": { ru: "прогноз погоды", phoneticRu: "prognoz pogody" },
  "thermometer": { ru: "термометр", phoneticRu: "termometr" },
  "degree": { ru: "градус", phoneticRu: "gradus" },
  "humidity": { ru: "влажность", phoneticRu: "vlazhnost'" },
  "pressure": { ru: "давление", phoneticRu: "davleniye" },
  // Emotions
  "joy/happiness": { ru: "радость", phoneticRu: "radost'" },
  "sadness": { ru: "грусть", phoneticRu: "grust'" },
  "anger/wrath": { ru: "гнев", phoneticRu: "gnev" },
  "fear/fright": { ru: "страх", phoneticRu: "strakh" },
  "surprise/amazement": { ru: "удивление", phoneticRu: "udivleniye" },
  "disgust": { ru: "отвращение", phoneticRu: "otvrasheniye" },
  "shame": { ru: "стыд", phoneticRu: "styd" },
  "guilt": { ru: "вина", phoneticRu: "vina" },
  "envy/jealousy": { ru: "зависть", phoneticRu: "zavist'" },
  "pride": { ru: "гордость", phoneticRu: "gordost'" },
  "gratitude": { ru: "благодарность", phoneticRu: "blagodarnost'" },
  "tenderness": { ru: "нежность", phoneticRu: "nezhnost'" },
  "compassion/sympathy": { ru: "сочувствие", phoneticRu: "sochuvstviye" },
  "disappointment": { ru: "разочарование", phoneticRu: "razocharovaniye" },
  "nostalgia": { ru: "ностальгия", phoneticRu: "nostal'giya" },
  "loneliness": { ru: "одиночество", phoneticRu: "odinochestvo" },
  "anxiety": { ru: "тревога", phoneticRu: "trevoga" },
  "panic": { ru: "паника", phoneticRu: "panika" },
  "despair": { ru: "отчаяние", phoneticRu: "otchayaniye" },
  "inspiration": { ru: "вдохновение", phoneticRu: "vdokhnoveniye" },
  "admiration/enthusiasm": { ru: "восхищение", phoneticRu: "voskhishcheniye" },
  "satisfaction/pleasure": { ru: "удовольствие", phoneticRu: "udovol'stviye" },
  "irritation/annoyance": { ru: "раздражение", phoneticRu: "razdrazheniye" },
  "boredom": { ru: "скука", phoneticRu: "skuka" },
  "enthusiasm": { ru: "энтузиазм", phoneticRu: "entuziazm" },
  "confidence": { ru: "уверенность", phoneticRu: "uverennost'" },
  "uncertainty": { ru: "неуверенность", phoneticRu: "neuverennost'" },
  "relief": { ru: "облегчение", phoneticRu: "oblegcheniye" },
  "excitement/worry": { ru: "волнение", phoneticRu: "volneniye" },
  "outrage/indignation": { ru: "возмущение", phoneticRu: "vozmushcheniye" },
  "patience": { ru: "терпение", phoneticRu: "terpeniye" },
  "impatience": { ru: "нетерпение", phoneticRu: "neterpeniye" },
  "calm/peace": { ru: "спокойствие", phoneticRu: "spokoystviye" },
  "confusion/embarrassment": { ru: "смущение", phoneticRu: "smushcheniye" },
  "wonder/astonishment": { ru: "изумление", phoneticRu: "izumleniye" },
  // Sports
  "football/soccer": { ru: "футбол", phoneticRu: "futbol" },
  "basketball": { ru: "баскетбол", phoneticRu: "basketbol" },
  "volleyball": { ru: "волейбол", phoneticRu: "voleybol" },
  "tennis": { ru: "теннис", phoneticRu: "tennis" },
  "hockey": { ru: "хоккей", phoneticRu: "khokkei" },
  "swimming": { ru: "плавание", phoneticRu: "plavaniye" },
  "running": { ru: "бег", phoneticRu: "beg" },
  "boxing": { ru: "бокс", phoneticRu: "boks" },
  "gymnastics": { ru: "гимнастика", phoneticRu: "gimnastika" },
  "figure skating": { ru: "фигурное катание", phoneticRu: "figurnoye kataniye" },
  "skiing/skis": { ru: "лыжи", phoneticRu: "lyzhi" },
  "ice skates": { ru: "коньки", phoneticRu: "kon'ki" },
  "cycling": { ru: "велоспорт", phoneticRu: "velosport" },
  "weightlifting": { ru: "тяжёлая атлетика", phoneticRu: "tyazhyolaya atletika" },
  "chess": { ru: "шахматы", phoneticRu: "shakhmaty" },
  "ball": { ru: "мяч", phoneticRu: "myach" },
  "goal": { ru: "гол", phoneticRu: "gol" },
  "score": { ru: "счёт", phoneticRu: "schyot" },
  "team": { ru: "команда", phoneticRu: "komanda" },
  "player": { ru: "игрок", phoneticRu: "igrok" },
  "coach/trainer": { ru: "тренер", phoneticRu: "trener" },
  "referee": { ru: "судья", phoneticRu: "sud'ya" },
  "champion": { ru: "чемпион", phoneticRu: "chempion" },
  "medal": { ru: "медаль", phoneticRu: "medal'" },
  "victory/win": { ru: "победа", phoneticRu: "pobeda" },
  "defeat/loss": { ru: "поражение", phoneticRu: "porazheniye" },
  "competition": { ru: "соревнование", phoneticRu: "sorevnovaniye" },
  "Olympics": { ru: "Олимпиада", phoneticRu: "Olimpiada" },
  "stadium": { ru: "стадион", phoneticRu: "stadion" },
  "gym": { ru: "спортзал", phoneticRu: "sportzal" },
  "swimming pool": { ru: "бассейн", phoneticRu: "basseyn" },
  "court (tennis)": { ru: "корт", phoneticRu: "kort" },
  "field/pitch": { ru: "поле", phoneticRu: "pole" },
  "finish line": { ru: "финиш", phoneticRu: "finish" },
  "start": { ru: "старт", phoneticRu: "start" },
  "record": { ru: "рекорд", phoneticRu: "rekord" },
  "exercise": { ru: "упражнение", phoneticRu: "uprazhneniye" },
  "warm-up": { ru: "разминка", phoneticRu: "razminka" },
  // Education
  "lesson": { ru: "урок", phoneticRu: "urok" },
  "subject (school)": { ru: "предмет", phoneticRu: "predmet" },
  "mathematics": { ru: "математика", phoneticRu: "matematika" },
  "physics": { ru: "физика", phoneticRu: "fizika" },
  "chemistry": { ru: "химия", phoneticRu: "khimiya" },
  "biology": { ru: "биология", phoneticRu: "biologiya" },
  "geography": { ru: "география", phoneticRu: "geografiya" },
  "history": { ru: "история", phoneticRu: "istoriya" },
  "literature": { ru: "литература", phoneticRu: "literatura" },
  "philosophy": { ru: "философия", phoneticRu: "filosofiya" },
  "economics": { ru: "экономика", phoneticRu: "ekonomika" },
  "psychology": { ru: "психология", phoneticRu: "psikhologiya" },
  "exam": { ru: "экзамен", phoneticRu: "ekzamen" },
  "test": { ru: "тест", phoneticRu: "test" },
  "grade/mark": { ru: "оценка", phoneticRu: "otsenka" },
  "homework": { ru: "домашнее задание", phoneticRu: "domashneye zadaniye" },
  "textbook": { ru: "учебник", phoneticRu: "uchebnik" },
  "exercise book": { ru: "тетрадь", phoneticRu: "tetrad'" },
  "diary/daybook": { ru: "дневник", phoneticRu: "dnevnik" },
  "schedule/timetable": { ru: "расписание", phoneticRu: "raspisaniye" },
  "break/recess": { ru: "перемена", phoneticRu: "peremena" },
  "class/classroom": { ru: "класс", phoneticRu: "klass" },
  "lecture hall": { ru: "аудитория", phoneticRu: "auditoriya" },
  "lecture": { ru: "лекция", phoneticRu: "lektsiya" },
  "seminar": { ru: "семинар", phoneticRu: "seminar" },
  "dissertation/thesis": { ru: "диссертация", phoneticRu: "dissertatsiya" },
  "diploma/degree": { ru: "диплом", phoneticRu: "diplom" },
  "scholarship/stipend": { ru: "стипендия", phoneticRu: "stipendiya" },
  "student (university)": { ru: "студент", phoneticRu: "student" },
  "pupil/student (school)": { ru: "ученик", phoneticRu: "uchenik" },
  "lecturer/instructor": { ru: "преподаватель", phoneticRu: "prepodavatel'" },
  "professor": { ru: "профессор", phoneticRu: "professor" },
  "rector/chancellor": { ru: "ректор", phoneticRu: "rektor" },
  "principal/director": { ru: "директор", phoneticRu: "direktor" },
  "blackboard": { ru: "доска", phoneticRu: "doska" },
  "chalk": { ru: "мел", phoneticRu: "mel" },
  "pencil": { ru: "карандаш", phoneticRu: "karandash" },
  "ruler": { ru: "линейка", phoneticRu: "lineyka" },
  "calculator": { ru: "калькулятор", phoneticRu: "kal'kulyator" },
  "microscope": { ru: "микроскоп", phoneticRu: "mikroskop" },
  "globe": { ru: "глобус", phoneticRu: "globus" },
  "library": { ru: "библиотека", phoneticRu: "biblioteka" },
  "dormitory": { ru: "общежитие", phoneticRu: "obshchezhitiye" },
  "faculty/department": { ru: "факультет", phoneticRu: "fakul'tet" },
  "department/chair": { ru: "кафедра", phoneticRu: "kafedra" },
  // Medicine
  "treatment": { ru: "лечение", phoneticRu: "lecheniye" },
  "diagnosis": { ru: "диагноз", phoneticRu: "diagnoz" },
  "symptom": { ru: "симптом", phoneticRu: "simptom" },
  "prescription/recipe": { ru: "рецепт", phoneticRu: "retsept" },
  "pill/tablet": { ru: "таблетка", phoneticRu: "tabletka" },
  "injection/shot": { ru: "укол", phoneticRu: "ukol" },
  "vaccine": { ru: "вакцина", phoneticRu: "vaktsina" },
  "antibiotic": { ru: "антибиотик", phoneticRu: "antibiotik" },
  "vitamin": { ru: "витамин", phoneticRu: "vitamin" },
  "operation/surgery": { ru: "операция", phoneticRu: "operatsiya" },
  "ambulance": { ru: "скорая помощь", phoneticRu: "skoraya pomoshch'" },
  "clinic/outpatient clinic": { ru: "поликлиника", phoneticRu: "poliklinika" },
  "hospital ward": { ru: "палата", phoneticRu: "palata" },
  "test/analysis": { ru: "анализ", phoneticRu: "analiz" },
  "X-ray": { ru: "рентген", phoneticRu: "rentgen" },
  "fever/temperature": { ru: "температура", phoneticRu: "temperatura" },
  "blood pressure": { ru: "давление", phoneticRu: "davleniye" },
  "pulse": { ru: "пульс", phoneticRu: "pul's" },
  "allergy": { ru: "аллергия", phoneticRu: "allergiya" },
  "asthma": { ru: "астма", phoneticRu: "astma" },
  "flu/influenza": { ru: "грипп", phoneticRu: "gripp" },
  "cold (illness)": { ru: "простуда", phoneticRu: "prostuda" },
  "headache": { ru: "головная боль", phoneticRu: "golovnaya bol'" },
  "runny nose": { ru: "насморк", phoneticRu: "nasmork" },
  "cough": { ru: "кашель", phoneticRu: "kashel'" },
  "high fever": { ru: "жар", phoneticRu: "zhar" },
  "wound": { ru: "рана", phoneticRu: "rana" },
  "bruise": { ru: "синяк", phoneticRu: "sinyak" },
  "fracture": { ru: "перелом", phoneticRu: "perelom" },
  "burn": { ru: "ожог", phoneticRu: "ozhog" },
  "poisoning": { ru: "отравление", phoneticRu: "otravleniye" },
  "inflammation": { ru: "воспаление", phoneticRu: "vospaleniye" },
  "infection": { ru: "инфекция", phoneticRu: "infektsiya" },
  "bandage": { ru: "бинт", phoneticRu: "bint" },
  "band-aid/plaster": { ru: "пластырь", phoneticRu: "plastyr'" },
  "syringe": { ru: "шприц", phoneticRu: "shprits" },
  "stethoscope": { ru: "стетоскоп", phoneticRu: "stetoskop" },
  "surgeon": { ru: "хирург", phoneticRu: "khirurg" },
  "therapist/GP": { ru: "терапевт", phoneticRu: "terapevt" },
  "pediatrician": { ru: "педиатр", phoneticRu: "pediatr" },
  "eye doctor/oculist": { ru: "окулист", phoneticRu: "okulist" },
  "health": { ru: "здоровье", phoneticRu: "zdorov'ye" },
  "immunity": { ru: "иммунитет", phoneticRu: "immunitet" },
  // Business
  "contract": { ru: "контракт", phoneticRu: "kontrakt" },
  "company": { ru: "компания", phoneticRu: "kompaniya" },
  "enterprise/business": { ru: "предприятие", phoneticRu: "predpriyatiye" },
  "firm": { ru: "фирма", phoneticRu: "firma" },
  "office": { ru: "офис", phoneticRu: "ofis" },
  "profit": { ru: "прибыль", phoneticRu: "pribyl'" },
  "loss (financial)": { ru: "убыток", phoneticRu: "ubytok" },
  "income/revenue": { ru: "доход", phoneticRu: "dokhod" },
  "expenses": { ru: "расходы", phoneticRu: "raskhody" },
  "budget": { ru: "бюджет", phoneticRu: "byudzhet" },
  "tax": { ru: "налог", phoneticRu: "nalog" },
  "salary/wage": { ru: "зарплата", phoneticRu: "zarplata" },
  "pension": { ru: "пенсия", phoneticRu: "pensiya" },
  "insurance": { ru: "страхование", phoneticRu: "strakhovaniye" },
  "loan/credit": { ru: "кредит", phoneticRu: "kredit" },
  "debt": { ru: "долг", phoneticRu: "dolg" },
  "percentage/interest rate": { ru: "процент", phoneticRu: "protsent" },
  "investment": { ru: "инвестиция", phoneticRu: "investitsiya" },
  "stock/share": { ru: "акция", phoneticRu: "aktsiya" },
  "stock exchange": { ru: "биржа", phoneticRu: "birzha" },
  "currency": { ru: "валюта", phoneticRu: "valyuta" },
  "Ukrainian currency unit": { ru: "гривна", phoneticRu: "grivna" },
  "dollar": { ru: "доллар", phoneticRu: "dollar" },
  "euro": { ru: "евро", phoneticRu: "yevro" },
  "bill/account": { ru: "счёт", phoneticRu: "schyot" },
  "check/receipt": { ru: "чек", phoneticRu: "chek" },
  "cash": { ru: "наличные", phoneticRu: "nalichnyye" },
  "card": { ru: "карта", phoneticRu: "karta" },
  "ATM": { ru: "банкомат", phoneticRu: "bankomat" },
  "partner": { ru: "партнёр", phoneticRu: "partnyor" },
  "client/customer": { ru: "клиент", phoneticRu: "kliyent" },
  "competitor": { ru: "конкурент", phoneticRu: "konkurent" },
  "supplier": { ru: "поставщик", phoneticRu: "postavshchik" },
  "manager": { ru: "менеджер", phoneticRu: "menedzher" },
  "director/CEO": { ru: "директор", phoneticRu: "direktor" },
  "accountant": { ru: "бухгалтер", phoneticRu: "bukhgalter" },
  "advertisement": { ru: "реклама", phoneticRu: "reklama" },
  "marketing": { ru: "маркетинг", phoneticRu: "marketing" },
  "goods/product": { ru: "товар", phoneticRu: "tovar" },
  "service": { ru: "услуга", phoneticRu: "usluga" },
  "discount": { ru: "скидка", phoneticRu: "skidka" },
  "order": { ru: "заказ", phoneticRu: "zakaz" },
  "delivery": { ru: "доставка", phoneticRu: "dostavka" },
  "warranty/guarantee": { ru: "гарантия", phoneticRu: "garantiya" },
  "return/refund": { ru: "возврат", phoneticRu: "vozvrat" },
  // Law & Government
  "law": { ru: "закон", phoneticRu: "zakon" },
  "right/law": { ru: "право", phoneticRu: "pravo" },
  "constitution": { ru: "конституция", phoneticRu: "konstitutsiya" },
  "government": { ru: "правительство", phoneticRu: "pravitel'stvo" },
  "parliament": { ru: "парламент", phoneticRu: "parlament" },
  "president": { ru: "президент", phoneticRu: "prezident" },
  "minister": { ru: "министр", phoneticRu: "ministr" },
  "deputy/member of parliament": { ru: "депутат", phoneticRu: "deputat" },
  "elections": { ru: "выборы", phoneticRu: "vybory" },
  "party (political)": { ru: "партия", phoneticRu: "partiya" },
  "democracy": { ru: "демократия", phoneticRu: "demokratiya" },
  "court": { ru: "суд", phoneticRu: "sud" },
  "crime": { ru: "преступление", phoneticRu: "prestupleniye" },
  "punishment": { ru: "наказание", phoneticRu: "nakazaniye" },
  "prison": { ru: "тюрьма", phoneticRu: "tyur'ma" },
  "police": { ru: "полиция", phoneticRu: "politsiya" },
  "witness": { ru: "свидетель", phoneticRu: "sviditel'" },
  "evidence/proof": { ru: "доказательство", phoneticRu: "dokazatel'stvo" },
  "fine/penalty": { ru: "штраф", phoneticRu: "shtraf" },
  "document": { ru: "документ", phoneticRu: "dokument" },
  "ID/certificate": { ru: "удостоверение", phoneticRu: "udostovereniye" },
  "citizenship": { ru: "гражданство", phoneticRu: "grazhdanstvo" },
  "embassy": { ru: "посольство", phoneticRu: "posol'stvo" },
  "consulate": { ru: "консульство", phoneticRu: "konsul'stvo" },
  "diplomacy": { ru: "дипломатия", phoneticRu: "diplomatiya" },
  "treaty/agreement": { ru: "договор", phoneticRu: "dogovor" },
  "sanction": { ru: "санкция", phoneticRu: "sanktsiya" },
  "protest": { ru: "протест", phoneticRu: "protest" },
  "rally/demonstration": { ru: "митинг", phoneticRu: "miting" },
  "referendum": { ru: "референдум", phoneticRu: "referendum" },
  // Military
  "army": { ru: "армия", phoneticRu: "armiya" },
  "military/troops": { ru: "войско", phoneticRu: "voysko" },
  "navy/fleet": { ru: "флот", phoneticRu: "flot" },
  "air force/aviation": { ru: "авиация", phoneticRu: "aviatsiya" },
  "general": { ru: "генерал", phoneticRu: "general" },
  "officer": { ru: "офицер", phoneticRu: "ofitser" },
  "sergeant": { ru: "сержант", phoneticRu: "serzhant" },
  "soldier": { ru: "солдат", phoneticRu: "soldat" },
  "weapon": { ru: "оружие", phoneticRu: "oruzhiye" },
  "tank": { ru: "танк", phoneticRu: "tank" },
  "rifle": { ru: "винтовка", phoneticRu: "vintovka" },
  "bullet": { ru: "пуля", phoneticRu: "pulya" },
  "bomb": { ru: "бомба", phoneticRu: "bomba" },
  "rocket/missile": { ru: "ракета", phoneticRu: "raketa" },
  "defense": { ru: "оборона", phoneticRu: "oborona" },
  "offensive/attack": { ru: "наступление", phoneticRu: "nastupleniye" },
  "battle": { ru: "битва", phoneticRu: "bitva" },
  "front (military)": { ru: "фронт", phoneticRu: "front" },
  "trench": { ru: "окоп", phoneticRu: "okop" },
  "headquarters": { ru: "штаб", phoneticRu: "shtab" },
  "intelligence/reconnaissance": { ru: "разведка", phoneticRu: "razvedka" },
  "prisoner of war": { ru: "военнопленный", phoneticRu: "voyennoplennyy" },
  "surrender/capitulation": { ru: "капитуляция", phoneticRu: "kapitulyatsiya" },
  "ceasefire/truce": { ru: "перемирие", phoneticRu: "peremiriye" },
  "hero": { ru: "герой", phoneticRu: "geroy" },
  // Tools
  "hammer": { ru: "молоток", phoneticRu: "molotok" },
  "screwdriver": { ru: "отвёртка", phoneticRu: "otvyortka" },
  "screw": { ru: "шуруп", phoneticRu: "shurup" },
  "nail": { ru: "гвоздь", phoneticRu: "gvozd'" },
  "saw": { ru: "пила", phoneticRu: "pila" },
  "drill": { ru: "дрель", phoneticRu: "drel'" },
  "pliers": { ru: "плоскогубцы", phoneticRu: "ploskogubcy" },
  "wrench": { ru: "гаечный ключ", phoneticRu: "gayechnyy klyuch" },
  "level (tool)": { ru: "уровень", phoneticRu: "uroven'" },
  "tape measure": { ru: "рулетка", phoneticRu: "ruletka" },
  "shovel": { ru: "лопата", phoneticRu: "lopata" },
  "rake": { ru: "грабли", phoneticRu: "grabli" },
  "axe": { ru: "топор", phoneticRu: "topor" },
  "ladder": { ru: "лестница", phoneticRu: "lestnitsa" },
  "bucket": { ru: "ведро", phoneticRu: "vedro" },
  "hose": { ru: "шланг", phoneticRu: "shlang" },
  "broom": { ru: "метла", phoneticRu: "metla" },
  "brush (painting)": { ru: "кисть", phoneticRu: "kist'" },
  "paint": { ru: "краска", phoneticRu: "kraska" },
  "glue": { ru: "клей", phoneticRu: "kley" },
  "tape (adhesive)": { ru: "скотч", phoneticRu: "skotch" },
  "rope": { ru: "верёвка", phoneticRu: "veryovka" },
  "wire": { ru: "проволока", phoneticRu: "provoloka" },
  "chain": { ru: "цепь", phoneticRu: "tsep'" },
  // Materials
  "wood (material)": { ru: "дерево", phoneticRu: "derevo" },
  "metal": { ru: "металл", phoneticRu: "metall" },
  "iron": { ru: "железо", phoneticRu: "zhelezo" },
  "steel": { ru: "сталь", phoneticRu: "stal'" },
  "copper": { ru: "медь", phoneticRu: "med'" },
  "gold": { ru: "золото", phoneticRu: "zoloto" },
  "aluminum": { ru: "алюминий", phoneticRu: "alyuminiy" },
  "glass (material)": { ru: "стекло", phoneticRu: "steklo" },
  "plastic": { ru: "пластик", phoneticRu: "plastik" },
  "rubber": { ru: "резина", phoneticRu: "rezina" },
  "leather": { ru: "кожа", phoneticRu: "kozha" },
  "fabric/cloth": { ru: "ткань", phoneticRu: "tkan'" },
  "cotton": { ru: "хлопок", phoneticRu: "khlopok" },
  "silk": { ru: "шёлк", phoneticRu: "shyolk" },
  "wool": { ru: "шерсть", phoneticRu: "sherst'" },
  "stone": { ru: "камень", phoneticRu: "kamen'" },
  "brick": { ru: "кирпич", phoneticRu: "kirpich" },
  "concrete": { ru: "бетон", phoneticRu: "beton" },
  "cement": { ru: "цемент", phoneticRu: "tsement" },
  "clay": { ru: "глина", phoneticRu: "glina" },
  "porcelain": { ru: "фарфор", phoneticRu: "farfor" },
  "paper (material)": { ru: "бумага", phoneticRu: "bumaga" },
  "cardboard": { ru: "картон", phoneticRu: "karton" },
  // Science
  "science": { ru: "наука", phoneticRu: "nauka" },
  "research/study": { ru: "исследование", phoneticRu: "issledovaniye" },
  "experiment": { ru: "эксперимент", phoneticRu: "eksperiment" },
  "theory": { ru: "теория", phoneticRu: "teoriya" },
  "hypothesis": { ru: "гипотеза", phoneticRu: "gipoteza" },
  "formula": { ru: "формула", phoneticRu: "formula" },
  "equation": { ru: "уравнение", phoneticRu: "uravneniye" },
  "molecule": { ru: "молекула", phoneticRu: "molekula" },
  "atom": { ru: "атом", phoneticRu: "atom" },
  "cell (biology)": { ru: "клетка", phoneticRu: "kletka" },
  "gene": { ru: "ген", phoneticRu: "gen" },
  "DNA": { ru: "ДНК", phoneticRu: "de-en-ka" },
  "evolution": { ru: "эволюция", phoneticRu: "evolyutsiya" },
  "gravity": { ru: "гравитация", phoneticRu: "gravitatsiya" },
  "energy": { ru: "энергия", phoneticRu: "energiya" },
  "electricity": { ru: "электричество", phoneticRu: "elektrichestvo" },
  "magnet": { ru: "магнит", phoneticRu: "magnit" },
  "heat": { ru: "тепло", phoneticRu: "teplo" },
  "wave": { ru: "волна", phoneticRu: "volna" },
  "particle": { ru: "частица", phoneticRu: "chastitsa" },
  "universe": { ru: "вселенная", phoneticRu: "vselennaya" },
  "galaxy": { ru: "галактика", phoneticRu: "galaktika" },
  "planet": { ru: "планета", phoneticRu: "planeta" },
  "star": { ru: "звезда", phoneticRu: "zvezda" },
  "satellite": { ru: "спутник", phoneticRu: "sputnik" },
  "space/cosmos": { ru: "космос", phoneticRu: "kosmos" },
  "astronaut": { ru: "космонавт", phoneticRu: "kosmonavt" },
  "telescope": { ru: "телескоп", phoneticRu: "teleskop" },
  "laboratory": { ru: "лаборатория", phoneticRu: "laboratoriya" },
  "scientist": { ru: "учёный", phoneticRu: "uchyonyy" },
  "discovery": { ru: "открытие", phoneticRu: "otkrytiye" },
  "invention": { ru: "изобретение", phoneticRu: "izobreteniye" },
  "robot": { ru: "робот", phoneticRu: "robot" },
  "artificial intelligence": { ru: "искусственный интеллект", phoneticRu: "iskusstvennyy intellekt" },
  // Music & Arts
  "music": { ru: "музыка", phoneticRu: "muzyka" },
  "song": { ru: "песня", phoneticRu: "pesnya" },
  "melody": { ru: "мелодия", phoneticRu: "melodiya" },
  "rhythm": { ru: "ритм", phoneticRu: "ritm" },
  "guitar": { ru: "гитара", phoneticRu: "gitara" },
  "piano": { ru: "пианино", phoneticRu: "pianino" },
  "violin": { ru: "скрипка", phoneticRu: "skripka" },
  "flute": { ru: "флейта", phoneticRu: "fleyta" },
  "drum": { ru: "барабан", phoneticRu: "baraban" },
  "trumpet": { ru: "труба", phoneticRu: "truba" },
  "Ukrainian stringed instrument": { ru: "бандура", phoneticRu: "bandura" },
  "Ukrainian wooden flute": { ru: "сопилка", phoneticRu: "sopilka" },
  "orchestra": { ru: "оркестр", phoneticRu: "orkestr" },
  "choir": { ru: "хор", phoneticRu: "khor" },
  "concert": { ru: "концерт", phoneticRu: "kontsert" },
  "opera": { ru: "опера", phoneticRu: "opera" },
  "ballet": { ru: "балет", phoneticRu: "balet" },
  "theater": { ru: "театр", phoneticRu: "teatr" },
  "performance/show": { ru: "спектакль", phoneticRu: "spektakl'" },
  "stage/scene": { ru: "сцена", phoneticRu: "stsena" },
  "role": { ru: "роль", phoneticRu: "rol'" },
  "director (film)": { ru: "режиссёр", phoneticRu: "rezhissyor" },
  "actress": { ru: "актриса", phoneticRu: "aktrisa" },
  "painting (art form)": { ru: "живопись", phoneticRu: "zhivopis'" },
  "sculpture": { ru: "скульптура", phoneticRu: "skul'ptura" },
  "architecture": { ru: "архитектура", phoneticRu: "arkhitektura" },
  "photography": { ru: "фотография", phoneticRu: "fotografiya" },
  "poetry": { ru: "поэзия", phoneticRu: "poeziya" },
  "prose": { ru: "проза", phoneticRu: "proza" },
  "novel": { ru: "роман", phoneticRu: "roman" },
  "poem": { ru: "стихотворение", phoneticRu: "stikhotvoreniye" },
  "fairy tale": { ru: "сказка", phoneticRu: "skazka" },
  "exhibition": { ru: "выставка", phoneticRu: "vystavka" },
  "gallery": { ru: "галерея", phoneticRu: "galereya" },
  "canvas": { ru: "холст", phoneticRu: "kholst" },
  "paintbrush": { ru: "кисточка", phoneticRu: "kistochka" },
  "oil paint": { ru: "масляная краска", phoneticRu: "maslyanaya kraska" },
  "watercolor": { ru: "акварель", phoneticRu: "akvarel'" },
  "Ukrainian embroidered shirt": { ru: "вышиванка", phoneticRu: "vyshivanka" },
  "pottery": { ru: "гончарство", phoneticRu: "goncharstvo" },
  // RU-only entries
  "to run (repeatedly)": { ru: "бегать", phoneticRu: "begat'" },
  "to walk/to go (repeatedly)": { ru: "ходить", phoneticRu: "khodit'" },
  "to fly (repeatedly)": { ru: "летать", phoneticRu: "letat'" },
  "to swim (repeatedly)": { ru: "плавать", phoneticRu: "plavat'" },
  "to drive/to ride (repeatedly)": { ru: "ездить", phoneticRu: "yezdit'" },
  "to fall": { ru: "падать", phoneticRu: "padat'" },
  "to go up/to climb": { ru: "подниматься", phoneticRu: "podnimat'sya" },
  "to go down/to descend": { ru: "спускаться", phoneticRu: "spuskat'sya" },
  "to turn": { ru: "поворачивать", phoneticRu: "povorachivat'" },
  "to stop": { ru: "останавливаться", phoneticRu: "ostanavlivat'sya" },
  "to return/to come back": { ru: "возвращаться", phoneticRu: "vozvrashchat'sya" },
  "to leave/to go away": { ru: "уходить", phoneticRu: "ukhodit'" },
  "to arrive/to come": { ru: "приходить", phoneticRu: "prikhodit'" },
  "to cross/to go across": { ru: "переходить", phoneticRu: "perekhodit'" },
  "to go out/to exit": { ru: "выходить", phoneticRu: "vykhodit'" },
  "to enter/to go in": { ru: "входить", phoneticRu: "vkhodit'" },
  "to carry (on foot)": { ru: "нести", phoneticRu: "nesti" },
  "to drag/to pull": { ru: "тащить", phoneticRu: "tashchit'" },
  "to roll": { ru: "катиться", phoneticRu: "katit'sya" },
  "to meet/to greet": { ru: "встречать", phoneticRu: "vstrechat'" },
  "to invite": { ru: "приглашать", phoneticRu: "priglashat'" },
  "to call (phone)": { ru: "звонить", phoneticRu: "zvonit'" },
  "to answer/to reply": { ru: "отвечать", phoneticRu: "otvechat'" },
  "to ask/to request": { ru: "просить", phoneticRu: "prosit'" },
  "to thank": { ru: "благодарить", phoneticRu: "blagodarit'" },
  "to apologize": { ru: "извиняться", phoneticRu: "izvinyat'sya" },
  "to greet/to say hello": { ru: "здороваться", phoneticRu: "zdorovat'sya" },
  "to say goodbye": { ru: "прощаться", phoneticRu: "proshchat'sya" },
  "to promise": { ru: "обещать", phoneticRu: "obeshchat'" },
  "to refuse/to decline": { ru: "отказываться", phoneticRu: "otkazyvat'sya" },
  "to argue/to debate": { ru: "спорить", phoneticRu: "sporit'" },
  "to scold": { ru: "ругать", phoneticRu: "rugat'" },
  "to advise": { ru: "советовать", phoneticRu: "sovetovat'" },
  "to communicate/to socialize": { ru: "общаться", phoneticRu: "obshchat'sya" },
  // Food RU-only
  "porridge/kasha": { ru: "каша", phoneticRu: "kasha" },
  "soup": { ru: "суп", phoneticRu: "sup" },
  "salad": { ru: "салат", phoneticRu: "salat" },
  "cake": { ru: "торт", phoneticRu: "tort" },
  "small pie/pastry": { ru: "пирожок", phoneticRu: "pirozhok" },
  "pancakes/blini": { ru: "блины", phoneticRu: "bliny" },
  "sour cream": { ru: "сметана", phoneticRu: "smetana" },
  "butter/oil": { ru: "масло", phoneticRu: "maslo" },
  "cheese": { ru: "сыр", phoneticRu: "syr" },
  "sausage": { ru: "колбаса", phoneticRu: "kolbasa" },
  "egg": { ru: "яйцо", phoneticRu: "yaytso" },
  "rice": { ru: "рис", phoneticRu: "ris" },
  "pasta/macaroni": { ru: "макароны", phoneticRu: "makarony" },
  "jam/preserves": { ru: "варенье", phoneticRu: "varen'ye" },
  "honey": { ru: "мёд", phoneticRu: "myod" },
  "cucumber": { ru: "огурец", phoneticRu: "ogurets" },
  "tomato": { ru: "помидор", phoneticRu: "pomidor" },
  "onion": { ru: "лук", phoneticRu: "luk" },
  "garlic": { ru: "чеснок", phoneticRu: "chesnok" },
  "pepper": { ru: "перец", phoneticRu: "perets" },
  "potato": { ru: "картофель", phoneticRu: "kartofel'" },
  "carrot": { ru: "морковь", phoneticRu: "morkov'" },
  "cabbage": { ru: "капуста", phoneticRu: "kapusta" },
  "beet": { ru: "свёкла", phoneticRu: "svyokla" },
  "bread": { ru: "хлеб", phoneticRu: "khleb" },
  "milk": { ru: "молоко", phoneticRu: "moloko" },
  "cottage cheese": { ru: "творог", phoneticRu: "tvorog" },
  "kefir": { ru: "кефир", phoneticRu: "kefir" },
  "sugar": { ru: "сахар", phoneticRu: "sakhar" },
  "salt": { ru: "соль", phoneticRu: "sol'" },
  "flour": { ru: "мука", phoneticRu: "muka" },
  "meat": { ru: "мясо", phoneticRu: "myaso" },
  "chicken": { ru: "курица", phoneticRu: "kuritsa" },
  "fish": { ru: "рыба", phoneticRu: "ryba" },
  "buckwheat": { ru: "гречка", phoneticRu: "grechka" },
  "dumplings/pelmeni": { ru: "пельмени", phoneticRu: "pel'meni" },
  "borscht": { ru: "борщ", phoneticRu: "borshch" },
  "cabbage soup/shchi": { ru: "щи", phoneticRu: "shchi" },
  "cold soup/okroshka": { ru: "окрошка", phoneticRu: "okroshka" },
  "frankfurter/sausage": { ru: "сосиска", phoneticRu: "sosiska" },
  "cutlet/patty": { ru: "котлета", phoneticRu: "kotleta" },
  "pie": { ru: "пирог", phoneticRu: "pirog" },
  "bread roll/bun": { ru: "булка", phoneticRu: "bulka" },
  "cookie/biscuit": { ru: "печенье", phoneticRu: "pechen'ye" },
  "candy/sweet": { ru: "конфета", phoneticRu: "konfeta" },
  "chocolate": { ru: "шоколад", phoneticRu: "shokolad" },
  "ice cream": { ru: "мороженое", phoneticRu: "morozhenoye" },
  "tea": { ru: "чай", phoneticRu: "chay" },
  "coffee": { ru: "кофе", phoneticRu: "kofe" },
  "juice": { ru: "сок", phoneticRu: "sok" },
  "water": { ru: "вода", phoneticRu: "voda" },
  "compote/stewed fruit drink": { ru: "компот", phoneticRu: "kompot" },
  "kvass": { ru: "квас", phoneticRu: "kvas" },
  "kissel (berry drink)": { ru: "кисель", phoneticRu: "kisel'" },
  "berry": { ru: "ягода", phoneticRu: "yagoda" },
  "apple": { ru: "яблоко", phoneticRu: "yabloko" },
  "pear": { ru: "груша", phoneticRu: "grusha" },
  "grapes": { ru: "виноград", phoneticRu: "vinograd" },
  "watermelon": { ru: "арбуз", phoneticRu: "arbuz" },
  "strawberry": { ru: "клубника", phoneticRu: "klubnika" },
  "raspberry": { ru: "малина", phoneticRu: "malina" },
  "cherry": { ru: "вишня", phoneticRu: "vishnya" },
  "plum": { ru: "слива", phoneticRu: "sliva" },
  "orange": { ru: "апельсин", phoneticRu: "apel'sin" },
  "lemon": { ru: "лимон", phoneticRu: "limon" },
  "banana": { ru: "банан", phoneticRu: "banan" },
  "mushrooms": { ru: "грибы", phoneticRu: "griby" },
  "nuts": { ru: "орехи", phoneticRu: "orekhi" },
  "sunflower seeds": { ru: "семечки", phoneticRu: "semechki" },
  "dill": { ru: "укроп", phoneticRu: "ukrop" },
  "parsley": { ru: "петрушка", phoneticRu: "petrushka" },
};

const usedEnKeys = new Set();
const outputWords = [];

for (const w of ukData.words) {
  const ruMatch = ruByEn[w.en] || manualRu[w.en];
  const entry = {
    uk: w.uk,
    ru: ruMatch ? ruMatch.ru : "???",
    en: w.en,
    phoneticUk: w.phonetic,
    phoneticRu: ruMatch ? ruMatch.phoneticRu : "???",
    category: w.category
  };
  if (entry.ru === "???") {
    console.error("MISSING RU for:", w.en);
  }
  outputWords.push(entry);
  usedEnKeys.add(w.en);
}

// Add RU-only entries with UK translations
const ukForRuOnly = {
  "to run (repeatedly)": { uk: "бігати", phoneticUk: "bihaty" },
  "to walk/to go (repeatedly)": { uk: "ходити", phoneticUk: "khodyty" },
  "to fly (repeatedly)": { uk: "літати", phoneticUk: "litaty" },
  "to swim (repeatedly)": { uk: "плавати", phoneticUk: "plavaty" },
  "to drive/to ride (repeatedly)": { uk: "їздити", phoneticUk: "yizdyty" },
  "to fall": { uk: "падати", phoneticUk: "padaty" },
  "to go up/to climb": { uk: "підніматися", phoneticUk: "pidnimatysya" },
  "to go down/to descend": { uk: "спускатися", phoneticUk: "spuskatysya" },
  "to turn": { uk: "повертати", phoneticUk: "povertaty" },
  "to stop": { uk: "зупинятися", phoneticUk: "zupynyatysya" },
  "to return/to come back": { uk: "повертатися", phoneticUk: "povertatysya" },
  "to leave/to go away": { uk: "йти геть", phoneticUk: "yty het" },
  "to arrive/to come": { uk: "приходити", phoneticUk: "prykhodyty" },
  "to cross/to go across": { uk: "переходити", phoneticUk: "perekhodyty" },
  "to go out/to exit": { uk: "виходити", phoneticUk: "vykhodyty" },
  "to enter/to go in": { uk: "входити", phoneticUk: "vkhodyty" },
  "to carry (on foot)": { uk: "нести", phoneticUk: "nesty" },
  "to drag/to pull": { uk: "тягти", phoneticUk: "tyahty" },
  "to roll": { uk: "котитися", phoneticUk: "kotytysya" },
  "to meet/to greet": { uk: "зустрічати", phoneticUk: "zustrichaty" },
  "to invite": { uk: "запрошувати", phoneticUk: "zaproshuvaty" },
  "to call (phone)": { uk: "дзвонити", phoneticUk: "dzvonyty" },
  "to answer/to reply": { uk: "відповідати", phoneticUk: "vidpovidaty" },
  "to ask/to request": { uk: "просити", phoneticUk: "prosyty" },
  "to thank": { uk: "дякувати", phoneticUk: "dyakuvaty" },
  "to apologize": { uk: "вибачатися", phoneticUk: "vybachatysya" },
  "to greet/to say hello": { uk: "вітатися", phoneticUk: "vitatysya" },
  "to say goodbye": { uk: "прощатися", phoneticUk: "proshchatysya" },
  "to promise": { uk: "обіцяти", phoneticUk: "obitsyaty" },
  "to refuse/to decline": { uk: "відмовлятися", phoneticUk: "vidmovlyatysya" },
  "to argue/to debate": { uk: "сперечатися", phoneticUk: "sperechatysya" },
  "to scold": { uk: "лаяти", phoneticUk: "layaty" },
  "to advise": { uk: "радити", phoneticUk: "radyty" },
  "to communicate/to socialize": { uk: "спілкуватися", phoneticUk: "spilkuvatysya" },
  "porridge/kasha": { uk: "каша", phoneticUk: "kasha" },
  "soup": { uk: "суп", phoneticUk: "sup" },
  "salad": { uk: "салат", phoneticUk: "salat" },
  "cake": { uk: "торт", phoneticUk: "tort" },
  "small pie/pastry": { uk: "пиріжок", phoneticUk: "pyrizhok" },
  "pancakes/blini": { uk: "млинці", phoneticUk: "mlyntsi" },
  "sour cream": { uk: "сметана", phoneticUk: "smetana" },
  "butter/oil": { uk: "масло", phoneticUk: "maslo" },
  "cheese": { uk: "сир", phoneticUk: "syr" },
  "sausage": { uk: "ковбаса", phoneticUk: "kovbasa" },
  "egg": { uk: "яйце", phoneticUk: "yaytse" },
  "rice": { uk: "рис", phoneticUk: "rys" },
  "pasta/macaroni": { uk: "макарони", phoneticUk: "makarony" },
  "jam/preserves": { uk: "варення", phoneticUk: "varennya" },
  "honey": { uk: "мед", phoneticUk: "med" },
  "cucumber": { uk: "огірок", phoneticUk: "ohirok" },
  "tomato": { uk: "помідор", phoneticUk: "pomidor" },
  "onion": { uk: "цибуля", phoneticUk: "tsybulya" },
  "garlic": { uk: "часник", phoneticUk: "chasnyk" },
  "pepper": { uk: "перець", phoneticUk: "perets" },
  "potato": { uk: "картопля", phoneticUk: "kartoplya" },
  "carrot": { uk: "морква", phoneticUk: "morkva" },
  "cabbage": { uk: "капуста", phoneticUk: "kapusta" },
  "beet": { uk: "буряк", phoneticUk: "buryak" },
  "bread": { uk: "хліб", phoneticUk: "khlib" },
  "milk": { uk: "молоко", phoneticUk: "moloko" },
  "cottage cheese": { uk: "сир кисломолочний", phoneticUk: "syr kyslomolochnyi" },
  "kefir": { uk: "кефір", phoneticUk: "kefir" },
  "sugar": { uk: "цукор", phoneticUk: "tsukor" },
  "salt": { uk: "сіль", phoneticUk: "sil" },
  "flour": { uk: "борошно", phoneticUk: "boroshno" },
  "meat": { uk: "м'ясо", phoneticUk: "myaso" },
  "chicken": { uk: "курка", phoneticUk: "kurka" },
  "fish": { uk: "риба", phoneticUk: "ryba" },
  "buckwheat": { uk: "гречка", phoneticUk: "hrechka" },
  "dumplings/pelmeni": { uk: "пельмені", phoneticUk: "pelmeni" },
  "borscht": { uk: "борщ", phoneticUk: "borshch" },
  "cabbage soup/shchi": { uk: "щі", phoneticUk: "shchi" },
  "cold soup/okroshka": { uk: "окрошка", phoneticUk: "okroshka" },
  "frankfurter/sausage": { uk: "сосиска", phoneticUk: "sosyska" },
  "cutlet/patty": { uk: "котлета", phoneticUk: "kotleta" },
  "pie": { uk: "пиріг", phoneticUk: "pyrih" },
  "bread roll/bun": { uk: "булка", phoneticUk: "bulka" },
  "cookie/biscuit": { uk: "печиво", phoneticUk: "pechyvo" },
  "candy/sweet": { uk: "цукерка", phoneticUk: "tsukerka" },
  "chocolate": { uk: "шоколад", phoneticUk: "shokolad" },
  "ice cream": { uk: "морозиво", phoneticUk: "morozyvo" },
  "tea": { uk: "чай", phoneticUk: "chay" },
  "coffee": { uk: "кава", phoneticUk: "kava" },
  "juice": { uk: "сік", phoneticUk: "sik" },
  "water": { uk: "вода", phoneticUk: "voda" },
  "compote/stewed fruit drink": { uk: "компот", phoneticUk: "kompot" },
  "kvass": { uk: "квас", phoneticUk: "kvas" },
  "kissel (berry drink)": { uk: "кисіль", phoneticUk: "kysil" },
  "berry": { uk: "ягода", phoneticUk: "yahoda" },
  "apple": { uk: "яблуко", phoneticUk: "yabluko" },
  "pear": { uk: "груша", phoneticUk: "hrusha" },
  "grapes": { uk: "виноград", phoneticUk: "vynohrad" },
  "watermelon": { uk: "кавун", phoneticUk: "kavun" },
  "strawberry": { uk: "полуниця", phoneticUk: "polunytsya" },
  "raspberry": { uk: "малина", phoneticUk: "malyna" },
  "cherry": { uk: "вишня", phoneticUk: "vyshnya" },
  "plum": { uk: "слива", phoneticUk: "slyva" },
  "orange": { uk: "апельсин", phoneticUk: "apelsyn" },
  "lemon": { uk: "лимон", phoneticUk: "lymon" },
  "banana": { uk: "банан", phoneticUk: "banan" },
  "mushrooms": { uk: "гриби", phoneticUk: "hryby" },
  "nuts": { uk: "горіхи", phoneticUk: "horikhy" },
  "sunflower seeds": { uk: "насіння соняшнику", phoneticUk: "nasinnya sonyashnyku" },
  "dill": { uk: "кріп", phoneticUk: "krip" },
  "parsley": { uk: "петрушка", phoneticUk: "petrushka" },
};

for (const w of ruData.words) {
  if (!usedEnKeys.has(w.en)) {
    const ukMatch = ukForRuOnly[w.en];
    if (ukMatch) {
      outputWords.push({
        uk: ukMatch.uk,
        ru: w.ru,
        en: w.en,
        phoneticUk: ukMatch.phoneticUk,
        phoneticRu: w.phonetic,
        category: w.category
      });
    } else {
      console.error("MISSING UK for RU-only:", w.en);
    }
  }
}

console.log("Total output words:", outputWords.length);
const missing = outputWords.filter(w => w.ru === "???" || w.phoneticRu === "???");
if (missing.length > 0) {
  console.error("MISSING entries:", missing.length);
  for (const m of missing) console.error("  ", m.en);
}

const output = { words: outputWords };
fs.writeFileSync(ukPath, JSON.stringify(output, null, 2), 'utf8');
console.log("Written to:", ukPath);
